### ISSUE TITLE
Error code is too value - Something went wrong! object of type 'NoneType' has no len()|

### ISSUE THREAD

**Issue by appchamp** [weaviate/Verba#10]
verba import --path data/minecraft/ --model "gpt-3.5-turbo" --clear True
✔ Client connected to local Weaviate server
ℹ All schemas available
ℹ Reading data/minecraft/minecraft_wiki.txt
ℹ Reading data/minecraft/minecraft_guide.txt
✔ Loaded 2 files
ℹ Converted data/minecraft/minecraft_wiki.txt
ℹ Converted data/minecraft/minecraft_guide.txt
✔ All 2 files successfully loaded

in the FE:
Q: how to play minecraft?
A: Something went wrong! object of type 'NoneType' has no len()|

**Comment by thomashacker** [comment]
This is interesting! Thanks a lot, we'll look into this

**Comment by mtichy92** [comment]
I also came across this error message - it was due to hitting OpenAI limits ("429 error: You exceeded your current quota, please check your plan and billing details."). But it can be anything within retrieve_semantic_cache() function.

**Comment by thomashacker** [comment]
You also need to embed the query you're sending to Verba, if your OpenAI key hits the request limit you'll always get the error. We're currently working on providing a complete open-source use of Verba, so you won't need to worry about limits like these in the future

**Comment by thomashacker** [comment]
This issue should be fixed with the new 0.3.0 version 🚀  Thanks a lot!
