### ISSUE TITLE
Can i use my local LLM model ?

### ISSUE THREAD

**Issue by tommy3266** [weaviate/Verba#102]
Can i use my local LLM model ?

**Comment by jcranney** [comment]
Is the model on HuggingFace? It's relatively straightforward to hack the Llama2Generator to use a user-defined HF model. If there is any interest I can make a pull request for something more user-friendly?

**Comment by clark-tax** [comment]
> Is the model on HuggingFace? It's relatively straightforward to hack the Llama2Generator to use a user-defined HF model. If there is any interest I can make a pull request for something more user-friendly?

I would be very interested in being able to plug verba into my self-hosted LLM models, and I suspect many others would be as well given the implications for data privacy. It would be great if there was an option to select arbitrary API endpoints. For example, many people self-host LLM models on API-enabled applications like this: https://github.com/oobabooga/text-generation-webui

**Comment by AvnerCohen** [comment]
Would love to see this too, maybe an example via ollama?
[This](https://github.com/weaviate/Verba/issues/81) seems to suggest such option is available, but I can't seem to get this to work :(

**Comment by moncefarajdal** [comment]
> Is the model on HuggingFace? It's relatively straightforward to hack the Llama2Generator to use a user-defined HF model. If there is any interest I can make a pull request for something more user-friendly?

Any idea on how to do this? I tried to copy the logic from Llama2Generator so I can use a new model "Falcon-7B" and I added it to the manager.py file but the app seems to not load the Falcon-7B model and keeps using either Llama if the env variable is set to true or GPT3 as default generator.

**Comment by thomashacker** [comment]
Great idea! We're working on this for the next update, making it easier to simply plug-in LLM's 🚀

**Comment by Plokkke** [comment]
Ollama is an open-source project that provides a server to run various models like Llama, Mistral, and others. I've created a connector/generator to utilize the Ollama server, which you can deploy locally or on-premises.

Feel free to reuse my branch to deploy your Verba server or wait for the merge. Currently, I'm encountering some issues with streaming responses, and I'm open to any help.

https://github.com/weaviate/Verba/pull/133

**Comment by thomashacker** [comment]
We added Ollama support! you can use your custom LLM served via ollama
