### ISSUE TITLE
RAGtriever Chat keep on showing forever processing DOT DOT DOT

### ISSUE THREAD

**Issue by frankyeung740422** [weaviate/Verba#106]
I am using Ubuntu with Python 3.11, I successfully deployed the Verba with all configured. I can add the documents, using token chunker and ADAEmbedder, everything works fine for the above three components as I can see those documents were splitted into chunks in the status windows. But when I tried to search in the RAGtriever chat windows, it just keep on showing DOT DOT DOT.. 

Below is the log files from the queries.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/Verba/goldenverba/server/api.py", line 596, in websocket_generate>
    payload = GeneratePayload.model_validate_json(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'GeneratePayload' has no attribute 'model_validate_>

During handling of the above exception, another exception occurred:

**Comment by thomashacker** [comment]
Thanks for the error message! We'll look into this

**Comment by sitaram70** [comment]
Frank
I got this error.  
What LLM are you using?
OpenAI or Cohere ....etc.?

I am using OpenAI.  When you use OpenAI, you have to add OPENAI_MODEL=gpt-3.5-turbo or OPENAI_MODEL=gpt-4-turbo-review parameter in the Verba environment section of compose-docker.yml file.
This step is missing in the docker-compse.yml file.

**Comment by thomashacker** [comment]
This should be fixed in the newest version! Let me know if the error persists
