### ISSUE TITLE
WebSocket Error: 'NoneType' object has no attribute 'pad_token' using docker setup with Llama

### ISSUE THREAD

**Issue by jeffreycwitt** [weaviate/Verba#107]
Hi all, newbie here. 

I'm trying to get a basic demo instance working using docker and LLama.

I've successively imported documents and I've set the following two configurations: 

- HF_TOKEN=$HF_TOKEN
- LLAMA2-7B-CHAT-HF=True

But when I ask the prompt a question I get the following error: 

    File "/Verba/goldenverba/server/api.py", line 599, in websocket_generate_stream
    verba-verba-1     |     async for chunk in manager.generate_stream_answer(
    verba-verba-1     |   File "/Verba/goldenverba/verba_manager.py", line 613, in generate_stream_answer
    verba-verba-1     |     async for result in self.generator_manager.selected_generator.generate_stream(
    verba-verba-1     |   File "/Verba/goldenverba/components/generation/Llama2Generator.py", line 77, in generate_stream
    verba-verba-1     |     if self.tokenizer.pad_token is None:
    verba-verba-1     | AttributeError: 'NoneType' object has no attribute 'pad_token'

I'm likely missing something simple, but I'm not sure what it is. Any advice is much appreciated.

**Comment by jeffreycwitt** [comment]
I think I resolved. I thought I had access to the Llama model, but I hadn't got approved for access yet.  (I'm sure the lack of the model actually be downloaded is at the root of this problem)

**Comment by jcranney** [comment]
Most likely the initialising of the `Llama2Generator` failed, so the `self.tokenizer` was never set. This failure only raises a warning which is easily lost in the docker logs:
https://github.com/weaviate/Verba/blob/1c9d4b49385315883ba0027ac1772a8b448f6204/goldenverba/components/generation/Llama2Generator.py#L26-L52

For me, it was related to the API Key I was using (for a fine-tuned HF Llama2 model), so I saw a message like:

> Repository Not Found for url: https://huggingface.co/universeTBD/astrollama-7b-chat-alpha/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

If you can't find the exception in the docker logs, it might be preferable to raise an error rather than just displaying the warning if the model isn't initialised - e.g., by removing the `try:` `except:` stuff in `Llama2Generator.py`:
```python
        if os.environ.get("LLAMA2-7B-CHAT-HF", "").lower() == "true":
            #try:
                import torch
                from transformers import AutoModelForCausalLM, AutoTokenizer

                def get_device():
                    if torch.cuda.is_available():
                        return torch.device("cuda")
                    elif torch.backends.mps.is_available():
                        return torch.device("mps")
                    else:
                        return torch.device("cpu")

                self.device = get_device()

                self.model = AutoModelForCausalLM.from_pretrained(
                    "meta-llama/Llama-2-7b-chat-hf",
                    device_map=self.device,
                )
                self.tokenizer = AutoTokenizer.from_pretrained(
                    "meta-llama/Llama-2-7b-chat-hf",
                    device_map=self.device,
                )
                self.model = self.model.to(self.device)
                msg.info("Loading Llama Model")
            #except Exception as e:
            #    msg.warn(str(e))
```

**Comment by RonZ-dev** [comment]
Make sure you are "authorised" to use it. https://huggingface.co/meta-llama/Llama-2-70b-chat-hf

**Comment by jeffreycwitt** [comment]
Hugging face says I've been authorized: 

<img width="879" alt="image" src="https://github.com/weaviate/Verba/assets/1146685/59e11b16-6098-47fe-a27e-3fd20bd8f7f7">

**Comment by jeffreycwitt** [comment]
I think I'm hitting a Docker memory limit when trying to install llama. 

Docker Build fro Verba gets this far:

<img width="879" alt="image" src="https://github.com/weaviate/Verba/assets/1146685/b641b398-401a-49a0-9bc8-08bda9b99ceb">

and then it just hangs.

Docker memory usage looks like it is very hight 12gb

![image](https://github.com/weaviate/Verba/assets/1146685/5dbd8663-61f4-4263-9abd-a7e6df5f2762)

And my docker resources setting is set to 12gb

![image](https://github.com/weaviate/Verba/assets/1146685/5896e861-41ed-414a-be2d-b98143f94887)

So I think the `pad_token` error is definitely coming from a failure to successfully install the llama model successfully. 

But this brings me to a resource question. 

Any ideas what the resources requirements are for running Verba with LLama2? How much memory do I need to allocate. M1 MacBook Pro only has 16GB. :(

**Comment by jeffreycwitt** [comment]
I raised Docker to 16 

and the build seems to be using all of it: 

![image](https://github.com/weaviate/Verba/assets/1146685/2dbe60e3-f443-4c38-bfc6-2d922a9d725b)

And still hanging...

Seems like this won't work for me, as it is too memory intensive for my machine. :(

Thanks for your tips and advice.
