### ISSUE TITLE
FR: incremental data ingest

### ISSUE THREAD

**Issue by zhibor** [weaviate/Verba#11]
It'd be great to allow incremental data ingestion to enhance efficiency and reduce API call costs. i.e., only ingest new or modified files with `verba import --path "Path to your dir or file" ..`

**Comment by thomashacker** [comment]
Yes, I agree! We're currently refactoring the data ingestion pipeline. We'll definitely implement your feedback!

**Comment by thomashacker** [comment]
With the new `0.3.0` update, we now have somewhat of an incremental data ingest, Verba now makes sure that existing data isn't imported again. However, modifying ingested data directly isn't implemented yet but will be in the future. Right now, the only way to modify existing data is to delete it and import it again.
