### ISSUE TITLE
What's document type?

### ISSUE THREAD

**Issue by cellulosa** [weaviate/Verba#110]
hi there and thank you for the great repo. I was wondering what does **Document type** actually do? It sets a (yellow) label, but I can't use it to filter documents e.g. select only those documents of type X. What's the purpose of that field?

**Comment by thomashacker** [comment]
Nice catch! 🚀 
The initial purpose of those fields was to filter documents when using RAG, but the feature isn't implemented yet. We are working on it for the next update!

**Comment by thomashacker** [comment]
We implemented label filtering in the newest update
