### ISSUE TITLE
Does verba support Chinese document?

### ISSUE THREAD

**Issue by tigermask1978** [weaviate/Verba#111]
If I have some document which content is chinese, what anything else to do so I can RAG with verba?
Thanks.

**Comment by eternnoir** [comment]
In my tests, simply importing the Chinese files and conversing directly in Chinese worked very well.

**Comment by thomashacker** [comment]
This depends on the type of embedder model and generator model you are using, if they are multilingual, then the answer is yes 😄 If you use models that were trained on just one language then they are limited to that only
