### ISSUE TITLE
OpenAI embeddings: text-embedding-3-large

### ISSUE THREAD

**Issue by mikehudson2** [weaviate/Verba#114]
Would be good to be able to have the option to use OpenAI's new 'large' embedding model. Would be interesting to see whether using more (3072) dimensions gives better retrieval of niche/unusual words.

[https://openai.com/blog/new-embedding-models-and-api-updates](url)

**Comment by bakongi** [comment]
https://github.com/weaviate/Verba/discussions/130

**Comment by thomashacker** [comment]
Great idea! We'll look into that for the next update 🚀

**Comment by thomashacker** [comment]
We added all OpenAI Embedding models in the newest release
