### ISSUE TITLE
Using a custom embedder

### ISSUE THREAD

**Issue by israaexol** [weaviate/Verba#119]
Hello,
I would like to use **a custom embedding model** hosted via the **HuggingFace** library other than the ones already available via the Verba interface (Mini-LM, Ada Embedder, and Cohere Embedder), but I can't seem to find a way to do that.
I tried connecting a Weaviate cluster but I don't know how I can add custom embedders to it as well.

I have the same inquiry about LLMs available via the HuggingFace interface and the possibility of using other ones in Verba other than LLAMA.

Could you please provide me with some guidance regarding this matter? I'd be most thankful!

Thank you in advance.

**Comment by moncefarajdal** [comment]
I'm also looking for this feature. I tried to hack into the Llama generator to use falcon-7b model from HuggingFace, but things seem not to be working. If anyone has already done it please let us know!
Thanks guys.

**Comment by bakongi** [comment]
Maybe this help
https://github.com/weaviate/Verba/issues/128#issue-2216314195

**Comment by thomashacker** [comment]
Great point! It would be a good idea to add some Resources for custom components!

**Comment by Mr-Jack-Tung** [comment]
I try this way:

File: manager.py

from transformers import AutoTokenizer
encoding = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
# encoding = tiktoken.encoding_for_model("gpt-3.5-turbo") # replace this code
...
item_tokens = encoding.encode(item_dict["content"], add_special_tokens=False)
...
truncated_content = encoding.decode(item_tokens[:remaining_space])

**Comment by thomashacker** [comment]
Good point! It is definitely something that can be improved! Your code will be helpful, thanks

**Comment by thomashacker** [comment]
Closing this for now
