### ISSUE TITLE
Any plan to implement custom API calls

### ISSUE THREAD

**Issue by CorentinvdBdO** [weaviate/Verba#12]
Hey I'd love to test your repository with my custom model hosted with a custom API (ex with oobabooga).

Do you plan on implementing calls to custom API or do you recommend to do it myself?

**Comment by thomashacker** [comment]
Yes, we plan to make it easy for anyone to plug in/implement their custom features, including custom models! We're currently refactoring the general codebase and architecture, I recommend implementing your custom API calls when the next iteration is out!

**Comment by CorentinvdBdO** [comment]
Thanks a lot for the answer, I'm glad to hear it!

**Comment by ashokrajab** [comment]
> Yes, we plan to make it easy for anyone to plug in/implement their custom features, including custom models! We're currently refactoring the general codebase and architecture, I recommend implementing your custom API calls when the next iteration is out!


Looking forward to this update.
