### ISSUE TITLE
can I run Verba on an air-gapped environment ?

### ISSUE THREAD

**Issue by ahadrez** [weaviate/Verba#120]
I am trying to run verba on an airgapped environment, I am getting the following error,  it seems like verba trying to connect to this URL 
```

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc58f81fdc0>: Failed to resolve 'openaipublic.blob.core.windows.net' ([Errno -2] Name or service not known)"))
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
```

**Comment by thomashacker** [comment]
Interesting use-case, have you set any OpenAI Keys? If not it's interesting to see that it still tries to create a connection?

**Comment by HakaishinShwet** [comment]
@thomashacker did you find and solution? because i am facing same error

**Comment by HakaishinShwet** [comment]
i even tried setting random openai key still got same error

**Comment by thomashacker** [comment]
We're looking into changing the openai implementation, I'll give an update here once we did that 👍

**Comment by kopparam** [comment]
Hi, I have the same issue. I have not set OpenAI keys. Only sey the ollama keys in env. 

Starting verba tries to connect to OpenAI

**Comment by thomashacker** [comment]
This should be fixed in the newest release
