### ISSUE TITLE
verba start >> ERROR - schema: dict, vectorizer: str, skip_properties: list[str] = None

### ISSUE THREAD

**Issue by gmoschese** [weaviate/Verba#121]
Hello everyone,

I'm facing an issue when attempting to start "verba" using the "verba start" command after following the installation steps outlined in the README.
The command results in an error, and the specific message I receive is: 

Traceback (most recent call last):
  File "venv/bin/verba", line 5, in <module>
    from goldenverba.server.cli import cli
  File "Verba/goldenverba/server/cli.py", line 6, in <module>
    from goldenverba.verba_manager import VerbaManager
  File "Verba/goldenverba/verba_manager.py", line 11, in <module>
    import goldenverba.components.schema.schema_generation as schema_manager
  File "Verba/goldenverba/components/schema/schema_generation.py", line 18, in <module>
    schema: dict, vectorizer: str, skip_properties: list[str] = None
TypeError: 'type' object is not subscriptable

I would appreciate any help or suggestions to resolve this issue.

Thank you!

**Comment by israaexol** [comment]
Hello, I had the same error at first and I believe it's related to the version of Python that you're using.
Being able to subscript a type has appeared in Python **3.9** and onwards.
Hope this helps!

**Comment by erinCodes3276** [comment]
I am receiving a similar error and using python 3.12.2

**Comment by alexbrooker** [comment]
I had to use python 3.11

**Comment by thomashacker** [comment]
Thanks for the issue! We're aware of the bug and will fix it 🚀

**Comment by thomashacker** [comment]
Should be fixed with the latest 0.4.0 version!
