### ISSUE TITLE
CSV data ingestion

### ISSUE THREAD

**Issue by thomharvey** [weaviate/Verba#126]
Is it possible to add data to Verba with csv files using unstructured.io? The unstructured API can process csv files, but I spoke with Erika Cardenas from Weaviate and she said Verba only supports PDF format and not csv.

**Comment by thomashacker** [comment]
Yes, Verba isn't supporting table data yet. But we're working on it for the next update

**Comment by thomharvey** [comment]
Thanks Edward. Do you know what the timeline is for the next update?

Kind Regards,

*Thom Harvey*

Tel: +250 789 184 030  (Rwanda)
Tel: +44 7736 937 471  (UK & Whatsapp)
www.kumva.io
www.petrichor.ventures <https://petrichor.ventures>

The contents of this message and any attachments are confidential and are
intended solely for the attention and use of the addressees only. The
information contained in this message may be subject to legal, professional
or other privilege or may be otherwise protected by other legal rules. If
you are not the intended recipient please contact the sender and delete
this message

**Comment by thomashacker** [comment]
Improving Ingestion and Chunking should be finished around May 🚀

**Comment by thomashacker** [comment]
Verba now supports CSV files as well in the newest 1.0.0 version!
