### ISSUE TITLE
Instruction: How to add Anthropic's Claude models

### ISSUE THREAD

**Issue by bakongi** [weaviate/Verba#129]
Hi everyone. As you know some latest Anthropic's Claude models is better and chaeper than OpenaAI models. So I create a new generator file to use Anthropic's models. and made changes to manager.py file in goldenverba/components/generation

[generation.zip](https://github.com/weaviate/Verba/files/14816283/generation.zip)

Install Anthropic library:
`pip install anthropic`

and you should add this variables to your environment (or .env file):

```
ANTHROPIC_API_KEY=sk-ant-api03-.....pAAA

ANTHROPIC_MODEL=claude-3-haiku-20240307
```
You will need API key from Anthropic at https://console.anthropic.com/

Available models:

Claude 3 Opus | claude-3-opus-20240229
-- | --
Claude 3 Sonnet | claude-3-sonnet-20240229
Claude 3 Haiku | claude-3-haiku-20240307

P.S.
The generator's code made with help of Claude and GPT-3.5/4

**Comment by thomashacker** [comment]
Great work! Thanks 🚀 We'll implement it in the coming next update

**Comment by bakongi** [comment]
I'd forgotten...

in "verba_manager.py" add:

```
        # Check Anthropic ENV KEY
        try:
            import anthropic

            anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "")

            if anthropic_key != "":
                self.environment_variables["ANTHROPIC_API_KEY"] = True
                anthropic.api_key = anthropic_key

        except Exception:
            self.environment_variables["ANTHROPIC_API_KEY"] = False
```
and

```
        try:
            import anthropic

            self.installed_libraries["anthropic"] = True
        except Exception:
            self.installed_libraries["anthropic"] = False
```

**Comment by bakongi** [comment]
it's enough to add the modification and restart Verba

**Comment by unityforge** [comment]
ok, strange. Nothing changed in my case after the modification...

**Comment by bakongi** [comment]
It depends on how did you installed Verba. If you installed from sources you should change in the souce folder, if you installed via pip you should make changes in the python lib folder where Verba was installed

**Comment by unityforge** [comment]
Indeed I installed from the source. What do you mean by "change in the source folder" ? Sorry for this novice question... I put the manager.py into goldenverba/components/generation and modified the .py files. Anything else to change?

**Comment by bakongi** [comment]
Try to rebuild. Change in sources, rebuild

**Comment by thomashacker** [comment]
We added anthropic to the newest release
