### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Mr-Jack-Tung** [weaviate/Verba#134]
![500 Internal Server Error](https://github.com/weaviate/Verba/assets/72214141/f97581dd-f4c5-4c13-be54-3ff7f3926735)

I using ollama docker and found this issues :(

**Comment by thomashacker** [comment]
Thanks for the issue! Can you share more information about your setup? Are you trying to use Ollama for generating answers ?

**Comment by thomashacker** [comment]
Oh, nice! Did you get it working? 😄 
The error code you showed initially might be related to the connection to your local Ollama instance. It's hard for me to debug it further since I don't know how you implemented it. If you share some bits of your code, we might be able to pin down the issue 🚀

**Comment by thomashacker** [comment]
Closing this for now
