### ISSUE TITLE
errors while executing "npm run dev"

### ISSUE THREAD

**Issue by sitaram70** [weaviate/Verba#139]
Development Server:

Launch the application in development mode by executing npm run dev.
Open your web browser and visit http://localhost:3000 to view the application.

When execute - npm run dev, I am getting several errors.

1.  at renderNodeDestructive (C:\Users\sitar\verba\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\sitar\Verba\frontend\node_modules\react\cjs\react.development.js:1618:21)
2.  at renderElement (C:\Users\sitar\verba\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)      
 ⨯ unhandledRejection: TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (C:\Users\sitar\Verba\frontend\node_modules\react\cjs\react.development.js:1626:21)

http://localhost:3000 is returning a blank page

**Comment by thomashacker** [comment]
Thanks for the issue! Which `node` version are you running?

**Comment by sitaram70** [comment]
I am using v20.12.2

**Comment by thomashacker** [comment]
Did `npm install` work without any issues for you? Do you know if these are the only error messages you get?

**Comment by sitaram70** [comment]
I got 1 critical and few others.  But resolved them my running npm audit fix and npm audit fix --force.

**Comment by sitaram70** [comment]
Should I try the same with different node version?  Any recommendation?
Please advise.

**Comment by thomashacker** [comment]
Could you try with node `v21.3.0`?
I will try to recreate your errors with `v20.12.2`

**Comment by sitaram70** [comment]
PS C:\Users\sitar\verba\frontend> node --version
v21.7.3

PS C:\Users\sitar\verba\frontend> npm install
added 517 packages, and audited 518 packages in 5m
217 packages are looking for funding
  run `npm fund` for details
  found 0 vulnerabilities
 PS C:\Users\sitar\verba\frontend> npm run dev   
> verba@0.3.1 dev
> next dev
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000
 ✓ Ready in 6s 
 ******************************************************************
 When I opened the htt://localhost:3000  I get several messages.  There are some errors as well.
 **some errros:**
 Import trace for requested module:
./node_modules/next/dist/client/components/router-reducer/reducers/get-segment-value.js
./node_modules/next/dist/client/components/layout-router.js

./node_modules/next/dist/client/components/router-reducer/reducers/navigate-reducer.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

********************
Import trace for requested module:
./node_modules/next/dist/client/components/router-reducer/reducers/prefetch-reducer.js
./node_modules/next/dist/client/components/router-reducer/router-reducer.js
./node_modules/next/dist/client/components/app-router.js

./node_modules/next/dist/client/components/router-reducer/reducers/prune-prefetch-cache.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

**************************
This message is repeated several times in the log

**Comment by thomashacker** [comment]
Thanks for the logs! What Operation System are you using?

It's an interesting error. I was not able to recreate the error you're having. Have you tried clearing your next cache and re-installing it in a clean environment?

**Comment by sitaram70** [comment]
Thank you for the response.
I am using Windows OU.
I deleted docker containers and images of Verba and weaviate.
I removed verba repository.  Restarted the PC.
PS C:\Users\sitar\> git clone https://github.com/weaviate/Verba.git
PS C:\Users\sitar> cd verba
PS C:\Users\sitar\verba>cd frontend
PS C:\Users\sitar\verba\frontend>npm install
added 525 packages, and audited 526 packages in 6m
218 packages are looking for funding
  run `npm fund` for details
4 vulnerabilities (1 low, 2 moderate, 1 critical)
To address issues that do not require attention, run:
  npm audit fix
To address all issues, run:
  npm audit fix --force
Run `npm audit` for details.
*********************************************************************
**PS C:\Users\sitar\verba\frontend> npm audit**
# npm audit report

@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
node_modules/@babel/traverse

next  0.9.9 - 13.5.4-canary.11
Severity: moderate
Next.js missing cache-control header may lead to CDN caching empty reply - https://github.com/advisories/GHSA-c59h-r6p8-q9wc
Depends on vulnerable versions of postcss
Depends on vulnerable versions of zod
fix available via `npm audit fix --force`
Will install next@13.5.6, which is outside the stated dependency range
node_modules/next

postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
fix available via `npm audit fix --force`
Will install next@13.5.6, which is outside the stated dependency range
node_modules/next/node_modules/postcss
node_modules/postcss

zod  <=3.22.2
Zod denial of service vulnerability - https://github.com/advisories/GHSA-m95q-7qp3-xv42
fix available via `npm audit fix --force`
Will install next@13.5.6, which is outside the stated dependency range
node_modules/zod

4 vulnerabilities (1 low, 2 moderate, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force
PS C:\Users\sitar\verba\frontend>
**********************
This is what I got this time.  I did not run the fix as I did it last time and did not fix the issue.
Please advise.

**Comment by thomashacker** [comment]
Thanks for the information! I'll try to recreate and debug your issue on a Windows device

**Comment by thomashacker** [comment]
It might be that some packages are not working on Windows but I need to clarify first

**Comment by sitaram70** [comment]
Thank you so much!
I want to work on modifying UX.

**Comment by sitaram70** [comment]
It worked for me.  I am able to the UI.

**Comment by sitaram70** [comment]
It worked for me. I am able to the UI.

**Comment by thomashacker** [comment]
That's great! What was your solution to get it working?

**Comment by sitaram70** [comment]
Created "npm" directory under ...AppData/Roaming/
That resolved the issue.
