### ISSUE TITLE
Error in instll setup

### ISSUE THREAD

**Issue by ashrafML** [weaviate/Verba#144]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken
Failed to build tiktoken
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects

**Comment by thomashacker** [comment]
Can you share more details about your Python Version?

**Comment by alitrack** [comment]
@ashrafML had better show the exception here. 
I just tried, it works on My Mac(both intel and m2 chips)

**Comment by thomashacker** [comment]
It seems that there are currently no wheels for tiktoken for python 3.12.0, for now i would recommend downgrading your python version to 3.11.0 or use the Docker deployment

**Comment by ashrafML** [comment]
@thomashacker  i will try this downgrade
