### ISSUE TITLE
Feat: Add baseURL config for Weaviate schema generation

### ISSUE THREAD

**Issue by samos123** [weaviate/Verba#147]
The generated schema doesn't seem to have an option to configure a base URL:
baseURL	string	Optional	https://api.openai.com	Sets a proxy or other URL instead of the default OpenAI URL.

Use a the protocol domain format: https://your.domain.com.

Currently you can only set the OPENAI base url for the LLM calls that Verba makes but the schemas generated by Verba do not correctly set the base URL.

**Comment by thomashacker** [comment]
Going to have a look at the PR! Thanks a lot
