### ISSUE TITLE
Error: TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by jpzhangvincent** [weaviate/Verba#15]
I installed from the source. And got this error:

`TypeError: issubclass() arg 1 must be a class`

**Comment by wobo-bhavin** [comment]
I am getting the same error, I installed using `pip`

**Comment by wobo-bhavin** [comment]
Update: I was able to get around it by creating a new virtualenv with `3.11.3`.  The Python version that was getting an error was `3.9.6`
