### ISSUE TITLE
Publish a docker image with tagged versions

### ISSUE THREAD

**Issue by samos123** [weaviate/Verba#153]
I created a separate repo so I can use a public docker image here in the helm charts: https://github.com/substratusai/verba-docker

However, ideally Verba publishes an official container image and tags it with each new release of verba. 

Note I'm fine with keeping my separate repo and publish container images but I might not be able to keep it up to date.

For example, I would like to see the following image published: `weaviate/verba:v0.4.0`

**Comment by thomashacker** [comment]
Great point! We'll look into that

**Comment by Japhys** [comment]
I second this!

**Comment by thomashacker** [comment]
Got sick last week 💀 Will continue working on it 🫡

**Comment by DavidSche** [comment]
+1

**Comment by thomashacker** [comment]
https://registry.hub.docker.com/r/semitechnologies/verba tada! 🥳
