### ISSUE TITLE
A file in the repository violates Windows naming rules

### ISSUE THREAD

**Issue by cookingboy3** [weaviate/Verba#155]
## Description
The filename ["The Influence of Detoxification Agents on the Intensity of Side Effects Caused by Medium-high Doses of Methotrexate in Children with Acute Lymphoblastic Leukemia: Case Series.pdf"](https://github.com/weaviate/Verba/blob/main/data/sana_maxima/The%20Influence%20of%20Detoxification%20Agents%20on%20the%20Intensity%20of%20Side%20Effects%20Caused%20by%20Medium-high%20Doses%20of%20Methotrexate%20in%20Children%20with%20Acute%20Lymphoblastic%20Leukemia%3A%20Case%20Series.pdf) contains a colon. [On Windows, this kind of behavior is considered especially heinous.](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) The bad path causes git to fail to clone the repository under typical conditions in Windows.

## Is this a bug or a feature?
- [ ] Bug
- [ ] Feature
- [x] File

## Steps to Reproduce
1. Get a Windows machine
2. Try to clone the repository

## Additional context
The file's very long filename may also cause spurious violations of the [Maximum Path Length Limitation](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) on Windows as well, under the right conditions. While the max path thing isn't as much of a problem anymore, you still have to opt-in to the new behavior under Windows 10.

**Comment by thomashacker** [comment]
Oh wow! I wasn't aware of that, nice catch. Thanks a lot, will be fixed immediately

**Comment by thomashacker** [comment]
Fixed and pushed to main, let me know if you can successfully clone the repo now

**Comment by cookingboy3** [comment]
Works! Thanks for the speedy fix.
