### ISSUE TITLE
 404 (Not Found) error at https://verba.weaviate.io/img/chunk.png

### ISSUE THREAD

**Issue by bakongi** [weaviate/Verba#157]
## Description
When attempting to access the image at https://verba.weaviate.io/img/chunk.png, a 404 (Not Found) error is returned.

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
1. Attempt to access the image at https://verba.weaviate.io/img/chunk.png.
2. Observe the 404 (Not Found) error.

**Comment by thomashacker** [comment]
Thanks, we're looking into this

**Comment by thomashacker** [comment]
Should be fixed with the latest release
