### ISSUE TITLE
Documents disappears from the view when selecting document type after pagination

### ISSUE THREAD

**Issue by bakongi** [weaviate/Verba#158]
## Description
When navigating to the "Documents" area and clicking on a specific page, such as Page 2, and subsequently selecting a document type, like "Blog", all documents disappear from the view. Refreshing the page is the only way to restore the document list.

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
1. Go to the "Documents" area.
2. Navigate to a specific page, e.g., Page 2.
3. Click on a document type, e.g., "Blog".

## Additional context
This issue disrupts the user experience by causing the disappearance of all documents when selecting a document type after navigating through pagination. Resolving this bug would ensure smoother navigation and usability within the "Documents" section.

## 1
![image](https://github.com/weaviate/Verba/assets/23183261/b1c7b69d-26a2-4f10-8789-29b825925b8c)
## 2
![Verba 1](https://github.com/weaviate/Verba/assets/23183261/b41de560-b38e-41f9-b65f-0ba29de2d680)

**Comment by thomashacker** [comment]
This is great feedback, thanks a lot! We'll look into fixing it

**Comment by thomashacker** [comment]
Should be fixed in the newest release
