### ISSUE TITLE
Feature Request: GraphRAG Support

### ISSUE THREAD

**Issue by ipdeft** [weaviate/Verba#159]
## Description
Will there be any plans to support GraphRAG approach within Verba?

## Is this a bug or a feature?
- [ ] Feature

## Additional context
https://www.microsoft.com/en-us/research/project/graphrag/
https://www.youtube.com/watch?v=r09tJfON6kE

**Comment by thomashacker** [comment]
Great idea! We will look into it

**Comment by ipdeft** [comment]
Appreciate you for even considering it. Awesome project btw.

**Comment by thomashacker** [comment]
Hey @ipdeft , unfortunately we decided to scope graphRAG out of the Verba project 😞 Sorry!

**Comment by joaorsbarbosa** [comment]
Would it be possible to expand on the decision?

 I am trying to add RAG to my workflow and Verba seems to be a great option but as I have to deal with a lot of datasheets, with lots acronyms and cross references, etc, the ommision of GraphRAG seems like it would be quite detrimental 

Thanks.
