### ISSUE TITLE
Uploading Json file doesn't work

### ISSUE THREAD

**Issue by preddy4690** [weaviate/Verba#160]
## Description
When I try to upload a json file, it shows the message 'Embedding completed with 1 Documents and 0 chunks in 0.0s

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
Verba Start. On the dashboard, click on 'Add Documents' button at the top. Click on Add Files and Choose a Json file. Click Import button.

## Additional context
Uploading PDFs works flawlessly. But Uploading .json files doesn't work.

**Comment by thomashacker** [comment]
Right now, Verba only accepts JSON files that looks like this:
We are still working on a general JSON import 

```json

{
    "text": "Your Text",
    "type": "Documentation",
    "name": "document_name",
    "path": "can_be_empty",
    "link": "if_you_want_to_link_to_the_source",
    "timestamp": "",
    "reader": "JSON",
    "meta": {},
    "chunks": []
}

```

**Comment by zaforcan** [comment]
> Right now, Verba only accepts JSON files that looks like this: We are still working on a general JSON import
> 
> ```json
> {
>     "text": "Your Text",
>     "type": "Documentation",
>     "name": "document_name",
>     "path": "can_be_empty",
>     "link": "if_you_want_to_link_to_the_source",
>     "timestamp": "",
>     "reader": "JSON",
>     "meta": {},
>     "chunks": []
> }
> ```

thanks, it worked for me. 
but i can't figure out how path, timestampt, meta and chunks areas are working.

text area is for content that will be chunk
type and name areas for document listing.. 
link is for "go to source" area

but i cant use meta, timestampt or chunks areas. When i'm asking a question, RAG is looking only text area.

**Comment by thomashacker** [comment]
I'll write up a guide in the README for ingesting JSON Files, explaining all fields. I'll give an update once we added it to the repo

**Comment by thomashacker** [comment]
JSON ingestion is now possible in the latest release!

**Comment by troublesprouter** [comment]
I don't understand the chunks field. Aren't the chunks generated by Verba according to the config settings we select before pressing "Import All"?

I have a ton of json data that I need to import, with important metadata, and I don't know how to.

How do I ingest something like this?


```
{
      "year": 1995,
      "number": "50",
      "title": "Circular Nº 50, del 13 de Diciembre de 1995 (modificada) (aclarada / complementada",
      "materia": "Crédito Tributario por inversiones en provincias de Arica y Parinacota",
      "url": "https://www.sii.cl/documentos/circulares/1995/circu50.pdf",
      "sin_efecto": false,
      "downloaded_filename": "circu50.pdf",
      "saved_filename": "circular_1995_50_2.pdf",
      "content": "Modificada por Circular Nº 45, del 3 de septiembre de 2008 \n\nModificadas por Circular Nº 64, del 6 de noviembre de 1996 \n\nComplementada por Circular Nº 64, del 6 de noviembre de 1996 \n\nCIRCULAR Nº 50, DEL 13 DE D ETC ETC etc",
      "modificada": true,
      "aclarada_complementada": true
    }
```


I need the document name to be set in the json, the content also set as key in the json, and the metadata be set in the json also. But I don't want to provide my own chunks. I want verba to produce the chunks, like it would with a pdf.

Is that possible? Thank you!
