### ISSUE TITLE
I am unable to open Verba in the browser at http://localhost:8000 using the docker instructions

### ISSUE THREAD

**Issue by ibbobud** [weaviate/Verba#162]
## Description
I am unable to open Verba in the browser at http://localhost:8000 using the docker instructions.  I am running ollama and updated the variables in the docker compose file and tried using different ports.  I am able to access port 8080 for the weaviate instance and ollama at port 11434 the web browser shows error "localhost didn’t send any data.  ERR_EMPTY_RESPONSE"

## Is this a bug or a feature?
- [X] Bug
- [ ] Feature

## Steps to Reproduce
Following the instructions provided on github for deploying with docker.  Running windows 11 with newest version of docker desktop.

## Additional context
No issues with other docker containers.

**Comment by ibbobud** [comment]
Current docker compose file.

---
version: '3.4'

services:
  verba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - WEAVIATE_URL_VERBA=http://localhost:8080
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - COHERE_API_KEY=$COHERE_API_KEY
      - OLLAMA_URL=http://localhost:11434
      - OLLAMA_MODEL=LLAMA3
      - UNSTRUCTURED_API_KEY=$UNSTRUCTURED_API_KEY
      - UNSTRUCTURED_API_URL=$UNSTRUCTURED_API_URL
      - GITHUB_TOKEN=$GITHUB_TOKEN
      ## IF YOU WANT AUTHENTICATION, UNCOMENT BELLOW 
      ## AND ADD WEAVIATE SERVICE
      #- WEAVIATE_API_KEY_VERBA=adminkey

    volumes:
      - ./data:/data/
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.24.2
    ports:
      - 8080:8080
      - 3000:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      OPENAI_APIKEY: $OPENAI_API_KEY
      COHERE_APIKEY: $COHERE_API_KEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai, generative-openai, qna-openai, text2vec-cohere'
      CLUSTER_HOSTNAME: 'node1'
      #######IF YOU WANT AUTHENTICATION UNCOMMENT BELOW########
      # AUTHENTICATION_APIKEY_ENABLED: 'true'
      # AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'readonlykey,adminkey'
      # AUTHENTICATION_APIKEY_USERS: 'jane@doe.com,john@doe.com'
      # AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      # AUTHORIZATION_ADMINLIST_USERS: 'john@doe.com'
      # AUTHORIZATION_ADMINLIST_READONLY_USERS: 'jane@doe.com'

volumes:
  weaviate_data: {}
...

**Comment by AdamLipina** [comment]
I have the same problem. The logs in docker have no errors but I can also only see the healthcheck. There are no other requests.

**Comment by ibbobud** [comment]
If i just leave the weaviate container running and then install verba on the localhost in a venv using pip install goldenverba using a .env with the ollama environment variables it will load up, I can embed text files but if I try and ask a question i get the following.

✔ Received query: Hello
⚠ Query failed: 'NoneType' object is not iterable
INFO:     127.0.0.1:55246 - "POST /api/query HTTP/1.1" 200 OK

**Comment by hholtmann** [comment]
The issue is that the verba server only listens on localhost and not on 0.0.0.0 inside the Docker container.
This should fix the issue:
https://github.com/weaviate/Verba/pull/163
After applying the fix do a `docker-compose build`

**Comment by thomashacker** [comment]
Thanks a lot for fixing! Great work
