### ISSUE TITLE
Admin Console not working in V1.0.1

### ISSUE THREAD

**Issue by sitaram70** [weaviate/Verba#165]
## Description

Admin Console not working in V1.0.1 on Ubuntu machine.

## Is this a bug or a feature?
- [ ] Bug
- [ ] Feature

## Additional context

I successfully made new version V1.0.1 and Ubuntu machine.
Everything is working fine except the Admin Console.
It shows it is "connecting..."
But never comes back with any data for Admin Console, Libraries and Variables.
Is there any port that I have to enable ...?
Please advise.

**Comment by thomashacker** [comment]
I think there might be some issues with the frontend connecting to the backend, can you check the developer logs on the frontend for any errors?

**Comment by sitaram70** [comment]
Please advise me on how /where to look for

**Comment by thomashacker** [comment]
Depending on your browser you should be able to open the developer mode with either `fn+f12` or `ctrl+f12`
This will open a console that will hopefully give us more insights into the errors

**Comment by sitaram70** [comment]
✔ Succesfully retrieved document:
e67dad93-3ea7-4836-b5ae-4f8b0a35e4e4
INFO:     173.224.98.234:52283 - "POST /api/get_document HTTP/1.1" 200 OK
INFO:     ('173.224.98.234', 52308) - "WebSocket /ws/generate_stream" [accepted]
INFO:     connection open
⚠ WebSocket connection closed by client.
INFO:     connection closed
This is what I found..but not sure that leads me any where

**Comment by sitaram70** [comment]
t.onclose = e=>{
                    e.wasClean ? console.log("WebSocket connection closed cleanly, code=".concat(e.code, ", reason=").concat(e.reason)) : console.error("WebSocket connection died"),
                    M("WebSocket Connection Offline", !0),
                    N(!1),
                    w("DONE")
                }

**Comment by sitaram70** [comment]
let {type: t, connected: s, isFetching: o, schemas: n, settingConfig: r, reset_verba: a} = e;
            return (0,
            l.jsxs)("div", {
                className: "flex flex-col gap-2",
                children: [(0,
                l.jsxs)("div", {
                    className: "flex flex-col bg-bg-alt-verba rounded-lg shadow-lg p-5 text-text-verba gap-6 h-[65vh] overflow-auto",
                    children: [(0,
                    l.jsxs)("div", {
                        className: "flex lg:flex-row flex-col gap-2",
                        children: [(0,
                        l.jsx)("p", {
                            className: "text-text-verba font-bold text-lg",
                            children: "Admin Console"
                        }), (0,
                        l.jsxs)("div", {
                            className: "flex gap-2",
                            children: [(0,
                            l.jsx)(D, {
                                status: null !== t,
                                true_text: t || "",
                                false_text: t || ""
                            }), (0,
                            l.jsx)(D, {
                                status: "Online" === s,
                                true_text: s,
                                false_text: "Connecting..."
                            })]
                        })]
                    }), o && (0,

**Comment by sitaram70** [comment]
What else I can try?

**Comment by thomashacker** [comment]
Hmm, these logs don't show any useful errors. Can you provide more information about how you start Verba and what Operating System you're using? Did you make sure to create a clean environment before installing Verba?

**Comment by sitaram70** [comment]
I am using AWS EC2 - t3.small, Ubuntu.
verba start --port 8000 --host 0.0.0.0

by default port 8000 is not working as it used to work in the earlier version.  So made explicit.

**Comment by sitaram70** [comment]
ubuntu@ip-172-31-55-26:~/Verba/goldenverba$ sudo lsof -i :6666
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python3   3425 ubuntu   18u  IPv4  37895      0t0  TCP localhost:48484->localhost:6666 (CLOSE_WAIT)
python3   3425 ubuntu   19u  IPv4  37983      0t0  TCP localhost:46718->localhost:6666 (CLOSE_WAIT)
weaviate- 3429 ubuntu  176u  IPv4  37880      0t0  TCP localhost:6666 (LISTEN)

Does this indicate something?

**Comment by sitaram70** [comment]
![image](https://github.com/weaviate/Verba/assets/132846352/ebffcbd6-a536-4610-a695-82901cb111e3)

**Comment by EscaticZheng** [comment]
same problem on Ubuntu 22.04

**Comment by thomashacker** [comment]
I still think there is an issue with the communication between the frontend and backend since the screenshot is also showing the ```connecting``` status, which indicates that the frontend is still trying to access the backend. 

It might be related to on which port and host you're running verba, but it's tricky to debug if we don't have any errors appearing. I would still recommend looking into the Developer Tools of the Frontend and looking at the console, it will give you errors if it can't connect to the backend

**Comment by beta-tank** [comment]
I've faced a similar issue: the socket connection closes immediately after opening the RAG page.
**Dev console output**
![Pasted image 20240522205554](https://github.com/weaviate/Verba/assets/2918385/b994f743-0d02-40a4-b9e0-724340006cf8)
`WebSocket connection closed cleanly, code=1005, reason=`

**Log from Verba docker container**
```
2024-05-22 20:52:21 INFO:     172.30.0.1:41744 - "GET /api/health HTTP/1.1" 200 OK
2024-05-22 20:52:21 INFO:     172.30.0.1:41744 - "GET /api/health HTTP/1.1" 200 OK
2024-05-22 20:52:21 ℹ Config Retrieved
2024-05-22 20:52:21 INFO:     172.30.0.1:41744 - "GET /api/config HTTP/1.1" 200 OK
2024-05-22 20:52:21 INFO:     ('172.30.0.1', 41754) - "WebSocket /ws/generate_stream" [accepted]
2024-05-22 20:52:21 INFO:     connection open
2024-05-22 20:52:21 INFO:     127.0.0.1:40360 - "HEAD / HTTP/1.1" 200 OK
2024-05-22 20:52:26 INFO:     127.0.0.1:40362 - "HEAD / HTTP/1.1" 200 OK
2024-05-22 20:52:31 INFO:     127.0.0.1:46586 - "HEAD / HTTP/1.1" 200 OK
2024-05-22 20:52:35 INFO:     connection closed
2024-05-22 20:52:36 ⚠ WebSocket connection closed by client.
2024-05-22 20:52:36 INFO:     127.0.0.1:46596 - "HEAD / HTTP/1.1" 200 OK
2024-05-22 20:52:41 INFO:     127.0.0.1:37146 - "HEAD / HTTP/1.1" 200 OK
2024-05-22 20:52:46 INFO:     127.0.0.1:37150 - "HEAD / HTTP/1.1" 200 OK
```

But I can add a new document.
```
2024-05-22 20:57:14 
2024-05-22 20:57:14   0%|          | 0/3451 [00:00<?, ?it/s]
2024-05-22 20:57:15   0%|          | 1/3451 [00:08<7:48:31,  8.15s/it]
2024-05-22 20:57:15   0%|          | 2/3451 [00:08<3:31:46,  3.68s/it]
```

Also I can't open the admin panel. On the "Status" page I got the same `WebSocket connection closed cleanly, code=1005, reason=` error and infinite `Connecting...` message. If I try to open it in a new tab on Weaviate admin port (9084 in my setup), there is no response.

## About my setup
Windows 11 pro 22H2
Ollama Windows setup. It is 100% working because I used it in another frontend and could add new documents through Verba and start a chat with them. CORS configuration is `OLLAMA_ORIGINS *`.
Varba run in Docker (WSL2).

**docker-compose.override.yml**
```
services:
  verba:
    ports: !override
      - 9085:8000
    environment:
      - WEAVIATE_URL_VERBA=http://weaviate:9084
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '9084'
      - --scheme
      - http
    ports:  !override
      - 9084:8080
      - 3000:8080
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:9084/v1/.well-known/ready || exit 1
      
```
I've overridden ports because the default ports are already used by other containers (the default ports are so popular).

**.env**
```
OLLAMA_URL=http://host.docker.internal:11434
OLLAMA_MODEL=llama3
```

**Comment by LotzF** [comment]
@thomashacker 

It's most likely a problem with the APIHost variable not getting a value when using anything but localhost.
Because of this parts like

`const fetchStatus = async () => {
    if (!APIHost) {
      return;
    }
...
`

within the StatusComponent.tsx are getting triggered.

**Comment by thomashacker** [comment]
Ah interesting! Great call, will definitely change this. Thanks a lot

**Comment by geraldatphotobucket** [comment]
I seemed to have the same issue. 

Running on a remote system.

Admin Console stuck saying 'Connecting...'

Launched the app using: verba start --host 0.0.0.0 --port 8888 

The web console has the following errors

page-a9dac4e4664785de.js:1 
        
        
       GET http://localhost:8000/api/health net::ERR_CONNECTION_REFUSED
e @ page-a9dac4e4664785de.js:1
ex @ page-a9dac4e4664785de.js:1
y @ page-a9dac4e4664785de.js:1
(anonymous) @ page-a9dac4e4664785de.js:1
aW @ fd9d1056-13318e87e7edaf08.js:1
oe @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
or @ fd9d1056-13318e87e7edaf08.js:1
ol @ fd9d1056-13318e87e7edaf08.js:1
id @ fd9d1056-13318e87e7edaf08.js:1
o @ fd9d1056-13318e87e7edaf08.js:1
T @ 23-5e3f67a9ac794630.js:1
23-5e3f67a9ac794630.js:1 Failed to fetch from http://localhost:8000/api/health: TypeError: Failed to fetch
    at e (page-a9dac4e4664785de.js:1:65338)
    at ex (page-a9dac4e4664785de.js:1:65495)
    at y (page-a9dac4e4664785de.js:1:66035)
    at page-a9dac4e4664785de.js:1:66664
    at aW (fd9d1056-13318e87e7edaf08.js:1:73243)
    at oe (fd9d1056-13318e87e7edaf08.js:1:84684)
    at ol (fd9d1056-13318e87e7edaf08.js:1:85322)
    at or (fd9d1056-13318e87e7edaf08.js:1:85206)
    at ol (fd9d1056-13318e87e7edaf08.js:1:85302)
    at or (fd9d1056-13318e87e7edaf08.js:1:85206)

Not sure if localhost:8000 is hard coded elsewhere.

If I understand correctly from the comment above a code fix is needed before this configuration can be supported?

**Comment by thomashacker** [comment]
I just merged @LotzF fix, you can try again by pulling the latest changes and re-installing Verba. Let me know if this fixes your issue

**Comment by beta-tank** [comment]
I can open the "Overview" tab on the latest release. Thanks!
![image](https://github.com/weaviate/Verba/assets/2918385/fec41f24-812b-4d05-94ea-69886dcf0fba)

**Comment by ForceMd** [comment]
So, I appear to be having the same issue as above, but except with the "goldenverba[huggingface]" install in place of the default "goldenverba" intall. To clarify, I am using Verba 1.0.3 with the Docker install. I am able to get the default configuration running without issue (can access all menu items), however, if I modify "Dockerfile" line 4 from "# RUN pip install -e '.'"  to "RUN pip install 'goldenverba[huggingface]'" I get similar symptoms as above. I.E. I can navigate to the "Chat", "Add Documents", "RAG" and "Settings" tabs without any errors, however, when I navigate to the "Overview" tab, I get a blank screen with "Admin Console Connecting...". In the  Verba docker container console, I get the same " ⚠ WebSocket connection closed by client." errors that @beta-tank was getting above. I do not get these errors if I change "Dockerfile" line 4 back to "# RUN pip install -e '.'" and prune / rebuild the docker image.

**Comment by sitaram70** [comment]
Setting are working now.
Thank you all for helping you all in fixing the issue.

**Comment by sitaram70** [comment]
I am able to save the settings successfully and also able to see all the details on the Admin page.
Thank you all for help in resolving the issue.
