### ISSUE TITLE
Settings are not being saved on Ubuntu

### ISSUE THREAD

**Issue by sitaram70** [weaviate/Verba#166]
## Description

Settings are not being saved on Ubuntu.  I made few changes to the Title page, logo etc. and applied.  When I clicked on chat, all my custom setting appears, and I got good summaries for the document that I imported.

However, once I refresh the page, all my custom configurations are gone.  How do I keep those changes.

## Is this a bug or a feature?
- [X ] Bug
- [] Feature

**Comment by thomashacker** [comment]
I think this issue is related to your other issue: https://github.com/weaviate/Verba/issues/165
Something is not working with the connection between the frontend and backend

**Comment by sitaram70** [comment]
I am able to save the settings successfully and also able to see all the details on the Admin page.
Thank you all for help in resolving the issue.

**Comment by sitaram70** [comment]
I am able to save the settings successfully and also able to see all the details on the Admin page.
Thank you all for help in resolving the issue.
