### ISSUE TITLE
"Query failed: 'NoneType' object is not iterable" Error when starting chat with imported documents

### ISSUE THREAD

**Issue by ibbobud** [weaviate/Verba#167]
After applying the fixes that were provided from a previous Issue that was converted to pull request 163.

Everything is working up to the point that I start a chat on the imported documents, and I get a red error message that says, "Query failed: 'NoneType' object is not iterable" that disappears, and the chat hangs up on "retrieving chunks".

If I look at the logs of the container I see the following.  Included some lines above and below for context.

INFO:     172.19.0.1:32800 - "POST /api/suggestions HTTP/1.1" 200 OK
INFO:     172.19.0.1:32800 - "POST /api/suggestions HTTP/1.1" 200 OK
✔ Received query: what is FAA part 14 about?
⚠ Query failed: 'NoneType' object is not iterable
INFO:     172.19.0.1:32800 - "POST /api/query HTTP/1.1" 200 OK
INFO:     127.0.0.1:53954 - "HEAD / HTTP/1.1" 200 OK

**Comment by thomashacker** [comment]
Thanks for the issue. Are you using OpenAI with Verba? I think, this might be related to an incompatible openai version.
If you're using OpenAI, what version are you using?

**Comment by cha0s** [comment]
I am using ollama and I get this error.
