### ISSUE TITLE
my only concern

### ISSUE THREAD

**Issue by gingibash** [weaviate/Verba#169]
## Description
is privacy???

do my docs and data become public to opeanai or whoever?

**Comment by thomashacker** [comment]
That's a valid concern! It depends on what service you choose to use Verba with. If you're using an OpenAI API Key, your data extracts will be sent to them to perform embedding and generation tasks. The same applies to any API Service.

However, you can also utilize local running models through ollama, making sure that no data leaves your company 🚀
