### ISSUE TITLE
Customize name + colours

### ISSUE THREAD

**Issue by vincentclaes** [weaviate/Verba#17]
Great job with Verba! 
I was really missing a tool like this to quickly prototype demo's for customers.

Would be great if we could document where we should rename what values in order to replace;

- "Verba" with "Customer X"
- Verba logo with my customer's logo
- Update CSS values with my customer's colours.

If you point me to the location, I can create a PR with some documentation.

**Comment by thomashacker** [comment]
Hey, thanks for the issue! Great idea; we hope to make it easy for users to customize the app (changing themes, title, etc.) in the coming versions 😄 If you need these changes now, you can have a look at the react frontend and fiddle around on your local fork to align it to your needs!

**Comment by thomashacker** [comment]
We implemented Frontend Customization in the newest v1.0.0 release!
