### ISSUE TITLE
Setting not saved

### ISSUE THREAD

**Issue by ipopcorn82** [weaviate/Verba#172]
After upgrading from version 0.4.0 to 1.0.1, I am unable to save the RAG settings. Specifically, changes to the embedding model or the LLM do not persist. When I click "Save" in the frontend, it appears that the settings are not being saved in the backend. In version 0.4.0, this functionality worked correctly, and I could see terminal notifications indicating that a component had been changed. Now, after clicking "Save," there is no such confirmation.

Is this a bug or a feature?
 Bug
 Feature
Steps to Reproduce
1. Go to http://127.0.0.1:8000/

2. Click on "RAG"
This message appears in the terminal: "
⚠ WebSocket connection closed by client.
INFO: connection closed"

3. Select a generator and change an LLM

4. After clicking save, I will forwarded to the verba chat interface but as you can see in the terminal, the settings were not saved
This message appears in the terminal:
INFO: ('127.0.0.1', 58615) - "WebSocket /ws/generate_stream" [accepted]
INFO: connection open
ℹ Document ID received: a9925877-0d84-4015-910d-87a25240e0ea
✔ Succesfully retrieved document:
a9925877-0d84-4015-910d-87a25240e0ea
INFO: 127.0.0.1:58616 - "POST /api/get_document HTTP/1.1" 200 OK

Additional context
In addition, upon starting Verba in the terminal and subsequently opening it in the browser, I encounter a "not found" error. This could potentially be related to the issue I've identified regarding the inability to save RAG settings after upgrading from version 0.4.0 to 1.0.1:

INFO: Started server process [18344]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: 127.0.0.1:58652 - "GET / HTTP/1.1" 200 OK
INFO: 127.0.0.1:58652 - "GET /icon.ico HTTP/1.1" 404 Not Found
INFO: 127.0.0.1:58655 - "GET /api/health HTTP/1.1" 200 OK
INFO: 127.0.0.1:58652 - "GET /api/health HTTP/1.1" 200 OK
INFO: 127.0.0.1:58652 - "GET /api/health HTTP/1.1" 200 OK
ℹ Config Retrieved

Browser: Brave, Edge
Verba version: 1.0.1
Python version: 3.10.11
Pip version: 24.0
Windows: Windows 11 Home, 23H2

**Comment by thomashacker** [comment]
Might be a problem with CORS, are you starting Verba on a different host?

**Comment by thomashacker** [comment]
Oh great catch! Thanks a lot, that's indeed a huge bug

**Comment by thomashacker** [comment]
Should be fixed in the latest release! Thanks for the catch
