### ISSUE TITLE
Question about using verba as a server

### ISSUE THREAD

**Issue by dwk601** [weaviate/Verba#179]
## Description
I wonder if I can use verba as a rag chatbot as server and use verba as api to implement to another website's chatbot. If there's a feature for this could you please explain me how?

## Is this a bug or a feature?
- [ ] Feature

**Comment by thomashacker** [comment]
You can use the existing fastapi app of Verba as a server and add a new frontend around it 🚀

**Comment by dwk601** [comment]
> You can use the existing fastapi app of Verba as a server and add a new frontend around it 🚀

is it the server/api.py?

**Comment by thomashacker** [comment]
Yes 👍
