### ISSUE TITLE
Load and display PDF files

### ISSUE THREAD

**Issue by vincentmin** [weaviate/Verba#18]
This is a feature request to add native support for PDF files.

My understanding is that Verba currently only handles text files such as `.txt` and `.md`. We can convert PDF files to text files to use them with Verba, but this will remove images and affect formatting. It would be great if we can load `.pdf` files directly into Verba and for the UI to display the PDF file with highlighted sections.

Since many other file formats can be converted to PDF without losing their formatting, this would greatly expand the use cases of Verba.

**Comment by thomashacker** [comment]
This issue should be implemented with the new 0.3.0 version 🚀  Thanks a lot!
