### ISSUE TITLE
 {'errors': {'error': [{'message': 'update vector: connection to: OpenAI API failed with status: 429 error: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.'}]}, 'status': 'FAILED'}

### ISSUE THREAD

**Issue by fengyunzaidushi** [weaviate/Verba#182]
## Description

![image](https://github.com/weaviate/Verba/assets/53250064/f385123c-9efa-4672-869a-b4cfe46c35bb)

(INFO) Importing...
(INFO) Importing 1 files with BasicReader
(INFO) Importing 2024-05-14-16-28-16_升级_Next.js_14.md
(SUCCESS) Loaded 1 documents in 0.0s
(INFO) Starting Chunking with TokenChunker
(SUCCESS) Chunking completed with 19 chunks in 0.01s
(INFO) Starting Embedding with ADAEmbedder
(ERROR) Embedding not successful: Chunk mismatch for 81ef7a62-e2f3-408c-a48a-68771055e1a0 0 != 19
(ERROR) Chunk mismatch for 81ef7a62-e2f3-408c-a48a-68771055e1a0 0 != 19
when add documents,it show the error:
```
 {'errors': {'error': [{'message': 'update vector: connection to: OpenAI API failed with status: 429 error: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.'}]}, 'status': 'FAILED'}
```
i use the third party openai provider,
i am sure my key is availbale ans have enough quota. and i think is the base_url dit not work,
## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce

git clone https://github.com/weaviate/Verba
pip install -e .

i just  modify the custome
OPENAI_BASE_URL
OPENAI_API_KEY
to the file .env
the .env path is same with the README.md
![image](https://github.com/weaviate/Verba/assets/53250064/174624de-c735-4dfa-9ba9-c89a604e633c)
![image](https://github.com/weaviate/Verba/assets/53250064/2fdd1b1e-1ab9-45d9-8cce-a15f112fc57e)

**Comment by thomashacker** [comment]
Try to reset Verba through the `Overview` tab to reset the schemas and to make sure that changes like BASE_URL are correctly configured. Let me know if this fixed your issue

**Comment by fengyunzaidushi** [comment]
i click the five buton on the left,but still the same error.
![image](https://github.com/weaviate/Verba/assets/53250064/079276e4-7661-4033-9dee-ab72137c0b3f)

**Comment by thomashacker** [comment]
Interesting! Did you check if both the `API_KEY` and `BASE_URL` are indeed correct? I would recommend writing a short script verifying that it works
