### ISSUE TITLE
Reminder to redo embeddings when changing embedding model

### ISSUE THREAD

**Issue by JanEggers-hr** [weaviate/Verba#184]
## Description

Don't we need a warning to redo the embeddings when switching models? AFAIK embeddings from, say, ADAembedder and a local model like llama3 are not compatible, nor are different local models. 

## Is this a bug or a feature?
- [ ] Bug
- [X] Feature

## Steps to Reproduce

Embed document, then switch to another embedder, then try to retrieve info from that first document

**Comment by thomashacker** [comment]
Good point! I'll look into making this more user-friendly!

**Comment by thomashacker** [comment]
Hey @JanEggers-hr , in the latest versions you'll get warned if you select an embedding model but haven't ingested any data with it yet. It will appear in the chat before writing any queries 🚀
