### ISSUE TITLE
Response using Ollama giving the instructions back

### ISSUE THREAD

**Issue by PrimeMoose3** [weaviate/Verba#185]
## Description

Inconsistent context retrieval and response generation. Responses sometimes default to a template or provide incorrect context.

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce

1. **Environment Setup**:
   - **.env File**:
     ```
     OLLAMA_URL=http://localhost:11434
     OLLAMA_MODEL=llama3
     ```

2. **Documents Uploaded**:
   - **personal_information.txt**:
     ```
     Name: John Doe
     Address: 123 Main Street, Anytown, USA 12345
     Email: johndoe@example.com
     Phone: 555-123-4567
     ```

## Additional context

Expected Behavior:
- Correctly retrieve and use context for responses.

Actual Behavior:
- Responses default to template or use incorrect context.

![image](https://github.com/weaviate/Verba/assets/46587568/16f3e403-2d89-48fd-aaa5-81e87552dea7)

**Comment by thomashacker** [comment]
I also encountered this error, but it's not related to Verba. I would recommend restarting the Ollama instance or update it. Let me know if this fixed it! 🚀
