### ISSUE TITLE
Llama model support

### ISSUE THREAD

**Issue by samos123** [weaviate/Verba#19]
Instead of using OpenAI, it would be cool if we could use Llama 2 instead.

If I made the PR and it works well, would you be open to merging it into this repo?

**Comment by gbecigneul** [comment]
that'd be great. I think the right way to do it would be via a custom module. Might be worth merging the pr directly to weaviate though, not only verba. 

https://weaviate.io/developers/weaviate/modules/other-modules/custom-modules

**Comment by thomashacker** [comment]
Hey, thanks a lot for the issue! This is a great idea, we're planning to support Llama in the next version and aim to make it easy for users to plug-in any custom model to Verba ⭐

**Comment by jeffbiocode** [comment]
@thomashacker 
When is this "next version" planned for release? Would love to see this integrated with Llama 2 and other open source LLMs

**Comment by thomashacker** [comment]
It should be coming in the next weeks! It will include Llama 2 support 🚀

**Comment by dustinchen93** [comment]
llama server can actually provide an interface similar to openai ([API like OAI](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md#api-like-oai)). I think this may provide a very simple compatibility method.

**Comment by thomashacker** [comment]
This issue should be implemented with the new 0.3.0 version 🚀  Thanks a lot!
