### ISSUE TITLE
[bug] Verba saves data in XDG_DATA_HOME (not ~/.local/share/weaviate)

### ISSUE THREAD

**Issue by LFd3v** [weaviate/Verba#191]
## Description
Basically what the title says.

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
1. Install Verba (https://github.com/weaviate/Verba#how-to-deploy-with-pip)
2. Start Verba (it will download weaviate-embedded)
3. Configure it to use Ollama
4. Import a document
5. Many files and directories with "verba" in their names, among other files, will be created ~/.local/share (i.e. XDG_DATA_HOME), there is no ~/.local/share/weaviate as shown in [README](https://github.com/weaviate/Verba#faq)

## Additional context
First of all, thank you a lot for developing, maintaining and providing the nice too as Open Source.

Environment:
1. ArchLinux
2. Pyhton 3.12
3. I actually have XDG_DATA_HOME defined in the login shell, maybe it makes some difference in your code

Please feel free to ask for more info if needed.

Regards

**Comment by thomashacker** [comment]
Nice catch! Thanks, I'll update the README

**Comment by thomashacker** [comment]
Verba is using Weaviate Embedded (https://weaviate.io/developers/weaviate/installation/embedded) per default, if no Weaviate Cluster is detected in the `.env` file. Weaviate automatically checks the `XDG_HOME_DATA` variable to save the data if not specified otherwise. I think, in this case, improving the documentation will make it clearer for users

**Comment by LFd3v** [comment]
Sure, agreed. But from what I recall reading it:
1. I does state that it would use weaviate-embedded if there is no other setup available
2. It is using XDG_DATA_HOME (which is ~/.local/share if not state otherwise).

Again, the main problem that I meant to report here is that all the files and folders are created inside XDG_DATA_HOME (or ~/.local/share) instead of creating a new folder there and then saving the working files inside this folder.

Or, in other others, it should save the files in ~/.local/share/weaviate (or $XDG_DATA_HOME/weaviate) as shown in the README, but it actually doesn't do it. 

I am sorry if this wasn't cleat before. Thank you again. Regards.

**Comment by thomashacker** [comment]
Good point! I'll look into documenting it better and fix the issue with data scattered inside `$XDG_DATA_HOME`
