### ISSUE TITLE
repeating the answer to the older questions in the chat

### ISSUE THREAD

**Issue by amihos** [weaviate/Verba#193]
## Description
verba keeps responding to older messages in the chat, ignoring newer ones

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
start a chat, ask one question, then move to the next question

## Additional context

![image](https://github.com/weaviate/Verba/assets/35190548/2f6d0c51-2fd0-42ec-a12d-73a4c6e1d973)

**Comment by amihos** [comment]
ollamaembeder

**Comment by thomashacker** [comment]
What specific Ollama Model are you using? Might be that the issue is related to the model you're using

**Comment by amihos** [comment]
llama 3

**Comment by thomashacker** [comment]
Have you tried other models as well?

**Comment by mike-mathieu** [comment]
This is happening to me as well. Using Ollama and OllamaImbedder. Once I turned off chat caching it seems to have stopped.

**Comment by thomashacker** [comment]
Should be fixed in the latest release! 😄
