### ISSUE TITLE
Windows is not supported with EmbeddedDB

### ISSUE THREAD

**Issue by Steph-m8** [weaviate/Verba#198]
It's probably a newbie problem. I can't find a way out, even with docker 

weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

**Comment by mmike87** [comment]
I had the same issue and "solved" it by installing it under Windows Subsystem for Linux. However, it doesn't seem to be able to connect Ollama running locally on the same machine.

**Comment by thomashacker** [comment]
If Docker does not work as well, another workaround can be to create a sandbox cluster on https://auth.wcs.api.weaviate.io/
