### ISSUE TITLE
front-end bug - boxes too big in document search

### ISSUE THREAD

**Issue by gbecigneul** [weaviate/Verba#20]
as you can see in below screenshot, boxes sizes not adjusted in document search tab. I tried both Chrome and Firefox. 

![Screenshot 2023-09-24 at 21 05 51](https://github.com/weaviate/Verba/assets/22099658/6d718943-bf70-40e3-9270-126741c23137)

**Comment by thomashacker** [comment]
Nice catch, this looks horrible! Will look into fixing that

**Comment by thomashacker** [comment]
This issue was fixed with the new 0.3.0 version 🚀  Thanks a lot!
