### ISSUE TITLE
ERROR intalling, python 3.12.3

### ISSUE THREAD

**Issue by VitaliyAT** [weaviate/Verba#206]
## Description
`Git clone` + `pip install -e .`
`ERROR: Could not install packages due to an OSError: [WinError 2] Не удается найти указанный файл: 'C:\\Python312\\Scripts\\tqdm.exe' -> 'C:\\Python312\\Scripts\\tqdm.exe.deleteme'`

## Is this a bug or a feature?
- [ ] Bug

## Steps to Reproduce
`Git clone` + `pip install -e .`

## Additional context
I am just trying install it. I have:
```
D:\Ai\Chat\Verba\try3>py -V
Python 3.12.3
```
ollama installed and run
```
PS C:\Users\1> ollama run llama3
pulling manifest
pulling 6a0746a1ec1a... 100% ▕████████████████████████████████████████████████████████▏ 4.7 GB
pulling 4fa551d4f938... 100% ▕████████████████████████████████████████████████████████▏  12 KB
pulling 8ab4849b038c... 100% ▕████████████████████████████████████████████████████████▏  254 B
pulling 577073ffcc6c... 100% ▕████████████████████████████████████████████████████████▏  110 B
pulling 3f8eb4da87fa... 100% ▕████████████████████████████████████████████████████████▏  485 B
verifying sha256 digest
writing manifest
removing any unused layers
success
>>> hi
Hi! How's it going?

>>> who are you?
I am LLaMA, a large language model trained by a team of researcher at Meta AI. My primary function is to
understand and respond to human input in a helpful and informative way. I'm here to assist you with any questions
or topics you'd like to discuss. I can provide information on a wide range of subjects, from science and history
to entertainment and culture. I can also help with language-related tasks such as language translation, grammar
correction, and text summarization.

I'm constantly learning and improving my responses based on the conversations I have with users like you. So, feel
free to ask me anything, and I'll do my best to provide a helpful and accurate response!

>>> Send a message (/? for help)
```

**Comment by VitaliyAT** [comment]
No, instruction nothing say about it and I already have Python 3.12.3 in system.
![image](https://github.com/weaviate/Verba/assets/1639608/38d7bc73-7860-4ead-8d05-540a2430068e)
By the way it will be necessary thing for project in any case, if Python's Virtual Environment will be added in project as part of it. THis soft is not along in OS, and it ask about some special soft for it self - so it expected action.

**Comment by VitaliyAT** [comment]
OK I see instruction below https://github.com/weaviate/Verba?tab=readme-ov-file#how-to-deploy-with-pip
Maybe it's my fault, but why the vague instructions (that was shown on my message higher) is doing in first place ?

**Comment by VitaliyAT** [comment]
Maybe I am newbie, but it give me chance see all errors. For professionals all this is "things that go without saying", but for newbies it is information halls. So for example instruction say:
`python3 -m virtualenv venv` - but no virtualenv installed. 
1) try insatll it - no luck yet. it's not trivial 'pip install virtualenv' - it give error
2) Why old `virtualenv `if we alredy have `venv`?

Other words want to say that 
1) instruction is not full as it should be. 
2) all this stuff can be automatized by installer.

**Comment by VitaliyAT** [comment]
Any way **pip installation** give error in the end, look at log file. Before commands in this file I install `virtualenv` by `py -m pip install --user virtualenv`
[Verba_install_log.txt](https://github.com/weaviate/Verba/files/15483597/Verba_install_log.txt)

**Comment by VitaliyAT** [comment]
https://github.com/weaviate/weaviate/issues/3315 - finaly it's this proble - It will not go normal on Windows =(

**Comment by thomashacker** [comment]
Windows is currently not supported for the local deployment, please either use the Docker or Weaviate Cluster deployment
