### ISSUE TITLE
collaboration features

### ISSUE THREAD

**Issue by mikestaub** [weaviate/Verba#207]
## Description
I want to be able to create a custom "brain" that is scoped to a set of documents and share it with ACL permissions.

## Is this a bug or a feature?
- [ ] Bug
- [x] Feature

## Additional context
See https://github.com/QuivrHQ/quivr for inspiration.

**Comment by thomashacker** [comment]
Interesting, we'll have a look

**Comment by thomashacker** [comment]
Hey @mikestaub, we decided to scope collaboration features out of Verba! Sorry 😞
