### ISSUE TITLE
Error in chat and importing documents: HTTPConnectionPool(host='host.docker.internal'

### ISSUE THREAD

**Issue by teldredge** [weaviate/Verba#208]
## Description
Error in chat and importing documents: HTTPConnectionPool(host='host.docker.internal'
I've seen similar issues to mine but not exactly the same setup so thought I'd post mine here.

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
~Started with a fresh ubuntu 20.04 desktop VM from iso, apt updated, upgraded.

~Installed and tested ollama locally:
	`curl -fsSL https://ollama.com/install.sh | sh`
	`ollama run llama3`

~Installed docker using apt installation method: https://docs.docker.com/engine/install/ubuntu/

~Post install steps to run docker without root- log in\out and tested with `docker run hello-world`

~Installed Verba via docker
	`git clone https://github.com/weaviate/Verba.git`
	`cp ~/Verba/goldenverba/.env.example ~/Verba/.env`
~Adjusted .env
                `OLLAMA_URL=http://localhost:11434`
		`OLLAMA_MODEL=llama3`
*also tried combinations with:
		`OLLAMA_URL=http://host.docker.internal:11434`
		`OLLAMA_MODEL=llama3:latest`

~At this point I'm able to reach Versa but chat and importing documents get the same error:
(ERROR) HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3f49132910>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))

**Comment by thomashacker** [comment]
Thanks for the issue, we'll have a closer look at the Docker Implementation with Ollama

**Comment by Akki-401** [comment]
> ## Description
> Error in chat and importing documents: HTTPConnectionPool(host='host.docker.internal' I've seen similar issues to mine but not exactly the same setup so thought I'd post mine here.
> 
> ## Is this a bug or a feature?
> * [x]  Bug
> * [ ]  Feature
> 
> ## Steps to Reproduce
> ~Started with a fresh ubuntu 20.04 desktop VM from iso, apt updated, upgraded.
> 
> ~Installed and tested ollama locally: `curl -fsSL https://ollama.com/install.sh | sh` `ollama run llama3`
> 
> ~Installed docker using apt installation method: https://docs.docker.com/engine/install/ubuntu/
> 
> ~Post install steps to run docker without root- log in\out and tested with `docker run hello-world`
> 
> ~Installed Verba via docker `git clone https://github.com/weaviate/Verba.git` `cp ~/Verba/goldenverba/.env.example ~/Verba/.env` ~Adjusted .env `OLLAMA_URL=http://localhost:11434` `OLLAMA_MODEL=llama3` *also tried combinations with: `OLLAMA_URL=http://host.docker.internal:11434` `OLLAMA_MODEL=llama3:latest`
> 
> ~At this point I'm able to reach Versa but chat and importing documents get the same error: (ERROR) HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f3f49132910>: Failed to resolve 'host.docker.internal' ([Errno -2] Name or service not known)"))

I'm also facing same issue...

**Comment by a-lang** [comment]
The container can't access to the localhost. Follow the steps below:
1. Edit the docker-compose.yml 
- OLLAMA_URL=$OLLAMA_URL
2. Edit the file .env
OLLAMA_URL="http://Your-IP-of-Ollama:11434"
NOTE: you have to ensure the ollama service works on the IP.
