### ISSUE TITLE
Suggesting: A demo usage on Google Colab.

### ISSUE THREAD

**Issue by mikebilly** [weaviate/Verba#21]
Please create a Google Colab notebook to demonstrate Verba's embedding and retrieval functions!

**Comment by thomashacker** [comment]
Great idea! We'll look into that, thanks

**Comment by thomashacker** [comment]
We do have a small Verba notebook (https://github.com/thomashacker/verba_notebook), but we haven't worked on a Google Collab just yet!

**Comment by thomashacker** [comment]
We're scoping out the Google Collab for now, sorry!
