### ISSUE TITLE
Querying previously created Weaviate database, Verba just says "no chunks available"

### ISSUE THREAD

**Issue by manolinux** [weaviate/Verba#210]
## Description
Querying previously created Weaviate database, Verba just says "no chunks available"
I don't know whether this is a bug or a feature. The system might not be prepared to load a pre-existing Weaviate database.
But it would be really nice to use an existing Weaviate instance, rather than uploading files one by one. But maybe our schema differs from what's required by Verba. Any tipos for this? Would really appreciate! 

## Is this a bug or a feature?
- [ ] Bug
- [x ] Feature

## Steps to Reproduce
Install Verba, point VERBA_WEAVIATE_URL to a preexisting Weaviate instance.
Try to make questions to documents there, but answering "no chunks available"
![image](https://github.com/weaviate/Verba/assets/4800102/0bf88b8a-70d7-4a41-81bb-bda86dee8867)

**Comment by thomashacker** [comment]
Verba currently depends on specific collection configurations, you need to upload your documents via Verba first to apply RAG on it.
