### ISSUE TITLE
Missing PathReader

### ISSUE THREAD

**Issue by abhishekbhakat** [weaviate/Verba#211]
## Description
The PathReader is mentioned in the change log but is not there in the latest version.

https://github.com/weaviate/Verba/blob/260a75af15ad8f4ec1cc2c74d2252b4687f70674/CHANGELOG.md?plain=1#L114

## Is this a bug or a feature?
- [ ] Bug
- [x] Feature

## Steps to Reproduce
No steps as the PathReader does not exist as per `managers.py`

https://github.com/weaviate/Verba/blob/260a75af15ad8f4ec1cc2c74d2252b4687f70674/goldenverba/components/managers.py#L44-L51

**Comment by thomashacker** [comment]
PathReader has been merged to the BasicReader for better UX

**Comment by abhishekbhakat** [comment]
Wait how to use that ?
