### ISSUE TITLE
Unable to add Documents

### ISSUE THREAD

**Issue by mmike87** [weaviate/Verba#213]
## Description
I have Ollama and Verba running under WSL on a Windows 11 system. Both are running, and both web interfaces are available in WSl and Windows. I can CURL to Verba from any WSL Window, and to Ollama from and WSL window as well. I set the allowed origins for Ollama to "all". TokenChunker and OllamaEmbedder are selected. 

However, when adding a document, I receive an error:

(ERROR) No connection adapters were found for '127.0.0.1:11434/api/embeddings'

## Is this a bug or a feature?
- [ X] Bug
- [ ] Feature

## Steps to Reproduce
I simply add a single PDF file from the "Add Documents" tab, and then select IMPORT. This may be something specific to my machine, but I have been unable to resolve it.

**Comment by mmike87** [comment]
Doh! ... needed to put HTTP in front of the 127.0.0.1 in the .env file ... hence the name "URL" in the file. :D

**Comment by thomashacker** [comment]
haha, so did it work after the change? 😄

**Comment by mmike87** [comment]
Yeah, that was the only issue with the import ... silly mistake on my part.

**Comment by 13777469818** [comment]
unsubscribe发自我的 iPhone在 2024年6月6日，19:52，mmike87 ***@***.***> 写道：﻿
Yeah, that was the only issue with the import ... silly mistake on my part.
