### ISSUE TITLE
Watch directories to keep vector DB up to date

### ISSUE THREAD

**Issue by francoisWeber** [weaviate/Verba#215]
## Description
The current way of ingesting files is static and must be done manually in the UI. In my opinion, it would be awesome to be able to "watch" directories and map changes directly to the DBs in order to maintain the knowledge up to date. 

## Is this a bug or a feature?
- [ ] Bug
- [x] Feature

## Additional context
Some preliminary steps are in PR here https://github.com/weaviate/Verba/pull/164 => ingestion directories.
Another "local RAG" project [PrivateGPT](https://docs.privategpt.dev/manual/document-management/ingestion) offers this kind of behaviour through the `watchdog` package. 

Thanks 🙃

**Comment by thomashacker** [comment]
Great idea! We'll add it to the list 🚀

**Comment by thomashacker** [comment]
Hey everyone! Unfortunately, we decided to scope this feature out of Verba! Sorry! 😞
