### ISSUE TITLE
Allow customisation of autocut value

### ISSUE THREAD

**Issue by jamesoflol** [weaviate/Verba#216]
## Description
Window retriever uses weaviate autocut(1). It delivers too few results for my use case, and probably others. It would be good if this was please customisable between like 1-3. Or just maybe setting traditional score cut off, and max number of chunk windows retrieved.

It would be good to also surface the score of each result in the web ui.

## Is this a bug or a feature?
- [ ] Bug
- [x] Feature

**Comment by thomashacker** [comment]
Yes, I agree! Good idea, we'll add it to the list

**Comment by thomashacker** [comment]
Added the configuration to the newest release!
