### ISSUE TITLE
Ollama in a different server.

### ISSUE THREAD

**Issue by monjurulkarim** [weaviate/Verba#218]
## Description
Hi, My ollama is installed in a different machine in the same local network. Can I use that ollama to a separate machine?

## Is this a bug or a feature?
- Feature

**Comment by thomashacker** [comment]
Interesting use case! I think, for that, you need to make sure that your Ollama machine is accessible through your local network, but I would recommend asking this question directly to the Ollama support since this is not related to Verba itself
