### ISSUE TITLE
Libraries version up

### ISSUE THREAD

**Issue by fammet-h** [weaviate/Verba#222]
## Description

I suggest versioning up libraries.

## Is this a bug or a feature?
- [ ] Bug
- [x] Feature

## Additional context

- weaviate-client 3.23.1 to >=3.26
    - When I tried to implement client.batch.delete_object with multiple conditions, the error occured.
- openai 0.27.9 to >1
    - When I tried to introduce ragas, the version conflict occured.

**Comment by thomashacker** [comment]
Fixed in the newest release
