### ISSUE TITLE
add domain parameter to serve Verba

### ISSUE THREAD

**Issue by priamai** [weaviate/Verba#226]
## Description
A typical user will want to host Verba behind a web proxy or a load balancer which will be fronted by a domain.

## Is this a bug or a feature?
- [X] Bug
- [ ] Feature

## Steps to Reproduce
Launch your Verba locally:

verba start --host localhost --port 8080

Then for example add an ngrok SSL proxy:
ngrok http --domain=mycooldomain.com 8080

This will result in a forever Loading Verba screen, because the api.ts file is hardcoded with localhost.

## Suggestion
I suggest to add another parameter into Verba which will then override the localhost in api.ts

For example:

verba start --host localhost --domain mycooldomain.com --port 8080

**Comment by priamai** [comment]
Also for reference I did also attempt to rewrite the host header:

```
verba start --host localhost --port 8080
ngrok http --domain=mycooldomain.com 8080 --host-header="localhost:8080"
```
and is still having the same issue.

**Comment by thomashacker** [comment]
Interesting use case! Thanks for the issue, we're looking into it 🚀

**Comment by Japhys** [comment]
I am running it behind nginx proxy manager and it seems to work, however it loads without the settings and documents i set via localhost, looks like a clean install. Kinda weird.

**Comment by thomashacker** [comment]
Hey everyone! I think the best solution here would be to host the frontend separately and move it behind your specific domain. Using the `verba start` is optimized and designed for local use only
