### ISSUE TITLE
frontend dev error

### ISSUE THREAD

**Issue by EscaticZheng** [weaviate/Verba#227]
## Description
npm run dev report:
 ✓ Compiled / in 8.8s (2246 modules)
 GET / 200 in 9585ms
 ✓ Compiled in 701ms (1108 modules)
 ✓ Compiled /_not-found in 252ms (2199 modules)
 GET /static/icon.ico 404 in 356ms
 GET /api/health 404 in 22ms
 GET /api/health 404 in 43ms
![image](https://github.com/weaviate/Verba/assets/107376080/5c4eb3e1-17d4-4de1-87e1-b1ddd18f4119)

no problem in npm run build. When I put icon.ico in the /frontend,  still report the /api/health 404
## Is this a bug or a feature?
- [√] Bug
- [ ] Feature

## Steps to Reproduce
Following the instruction in FRONTEND.md. npm run dev. Then open localhost:3000.

## Additional context
nodejs v22.3.0

**Comment by thomashacker** [comment]
Thanks for the issue, we're looking into it

**Comment by thomashacker** [comment]
Ah I see, you need to start the verba server, so the frontend can communicate with it

**Comment by SaiAkhil066** [comment]
those two folders should be in the same path?
I have started my backend also, but the same error is showing... what may be the issue pertains?

**Comment by thomashacker** [comment]
Can you share more information about what you're trying to do, thanks!
