### ISSUE TITLE
Chunk Mismatch Error on Coolify

### ISSUE THREAD

**Issue by DannyBoy5240** [weaviate/Verba#229]
Hi
I installed Verba on Coolify by Docker Compose.
But it didn't run so I changed port numbers to 9000 (Verba), and 9090 (Weaviate).
Now both of them can start but it doesn't work at all.
But while importing a common text pdf file, the error of 'Chunk mismatch for' occurs and gets failed.
Who can help me for this issue?

![image](https://github.com/weaviate/Verba/assets/114929153/17c166d9-03ca-4c22-a410-509386bcdded)

**Comment by thomashacker** [comment]
Hey thanks for the issue, is this also happening for normal .txt files? Or is this specific to .pdf?

**Comment by DannyBoy5240** [comment]
Thanks for your care.
Yes, it is common for .txt and .pdf.
Is there any other way to install on Coolify?

**Comment by thomashacker** [comment]
Thanks for the info. I'm not sure if this issue is related to Coolify itself. I wonder if it's related to your Cohere Key? 
Can you verify that your selected API key works and has enough credits? 😄

**Comment by coderjunc** [comment]
> Thanks for your care. Yes, it is common for .txt and .pdf. Is there any other way to install on Coolify?

Where have you disappeared to? Are you even alive???! Why do you ignore every single text and email I send? How could you just leave in the middle of everything, leaving me to suffer like this? This pain is unbearable and it's all because of you. Why are you doing this to me? Why?

**Comment by coderjunc** [comment]
> Hi I installed Verba on Coolify by Docker Compose. But it didn't run so I changed port numbers to 9000 (Verba), and 9090 (Weaviate). Now both of them can start but it doesn't work at all. But while importing a common text pdf file, the error of 'Chunk mismatch for' occurs and gets failed. Who can help me for this issue?
> 
> ![image](https://private-user-images.githubusercontent.com/114929153/343817330-17c166d9-03ca-4c22-a410-509386bcdded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjQzMDMsIm5iZiI6MTcyNzQ2NDAwMywicGF0aCI6Ii8xMTQ5MjkxNTMvMzQzODE3MzMwLTE3YzE2NmQ5LTAzY2EtNGMyMi1hNDEwLTUwOTM4NmJjZGRlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxOTA2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDVjZTM2Mzk5N2JiMWEzMzVlODE2YzkxNDhlZDNmOGU3ZGUxNTBkMGM5OGM5NjQ2ZTA2ZmUxM2ExMmE3ZDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LzsLBzDsDby1fgDo587EbydemmiUHXpgDHnXX4cg8ak)

😭😭😭😭😭😭
