### ISSUE TITLE
Unable to Deploy on Coolify | Chunk Mismatch Error

### ISSUE THREAD

**Issue by coderjunc** [weaviate/Verba#232]
![image](https://github.com/weaviate/Verba/assets/170351869/26bf4405-54bf-41c8-bc56-09dd5cd5b827)
![image](https://github.com/weaviate/Verba/assets/170351869/2640be38-2784-4af8-924e-7656c0abc13b)

Even the unstructured API doesn't work, unable to import any file.

**Comment by thomashacker** [comment]
Thanks for the issue, seems like there is an issue with Coolify and Verba. https://github.com/weaviate/Verba/issues/229
We'll look into this 🚀

**Comment by thomashacker** [comment]
We just released the new v2 version, could you try again on Coolify?
