### ISSUE TITLE
The ability to specify which context to use

### ISSUE THREAD

**Issue by olegius88** [weaviate/Verba#235]
## Description
Greetings. Is it possible to specify in the chat which uploaded documents to use as context?

## Is this a bug or a feature?
- [*] Feature

## Additional context
It is planned to use Verba as an assistant for chat consultants to generate responses depending on the context of the current correspondence, as well as the context related to currently operating services and available goods. You need to be able to control which context to use. For example, it can be file names or something else.

**Comment by thomashacker** [comment]
Great idea! Document Filtering will come soon 🚀

**Comment by olegius88** [comment]
To implement this feature, you only need to refine Verba in terms of query processing? Or is there a need for improvement at the database level?

**Comment by thomashacker** [comment]
Yes, you would simply add filters to the query. Additionally, you need to add the required UI elements, API changes, etc.
But should be straightforward, I'll give an update once we implemented it 😄
