### ISSUE TITLE
InputText’ object has no attribute ‘model_dump’

### ISSUE THREAD

**Issue by L-Huber** [weaviate/Verba#244]
## Is this a bug or a feature?
- [ x] Bug
- [ ] Feature

## Steps to Reproduce

Installed verba using an m1 MacBook and python 3.10
## Additional context
I got the following error while installing it locally:
AttributeError: ‘InputText’ object has no attribute ‘model_dump’

Server Setup Information
hlib>=1.1.0->weaviate-client==3.23.1->goldenverba) (1.15.1)
Python: 3.10

Any additional Information
:information_source: Setting up client
:information_source: Using Weaviate Embedded
Started /Users/?/.cache/weaviate-embedded: process ID 54469
{“action”:“startup”,“default_vectorizer_module”:“none”,“level”:“info”,“msg”:“the default vectorizer modules is set to "none", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer”,“time”:“2024-06-27T15:34:13+02:00”}
{“action”:“startup”,“auto_schema_enabled”:true,“level”:“info”,“msg”:“auto schema enabled setting is set to "true"”,“time”:“2024-06-27T15:34:13+02:00”}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_cache_minilm_4iD4rqcKWgVO”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:61916}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_cache_ollama_wD58RBlbk2fn”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:222500}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_cache_text2vec_cohere_HAy7I9ZAaQEs”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:60625}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_cache_text2vec_openai_i9TxFte4fEW6”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:53209}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_chunk_minilm_uxj6Ir4EWkyx”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:57833}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_chunk_ollama_mvMMPMO7aPus”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:57500}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_chunk_text2vec_cohere_XHmRLDFh8MaI”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:56333}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_chunk_text2vec_openai_4CrqldHwQ1by”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:52834}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_config_ewWGsf7RRhSJ”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:58458}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_document_minilm_v3v7eeBXiJlT”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:62209}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_document_ollama_v5TeWWj2wow1”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:58875}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_document_text2vec_cohere_IjKVe10s5dWq”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:77750}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_document_text2vec_openai_feVObhdfshEL”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:57416}
{“action”:“hnsw_vector_cache_prefill”,“count”:3000,“index_id”:“verba_suggestion_OeZouxOz6R3V”,“level”:“info”,“limit”:1000000000000,“msg”:“prefilled vector cache”,“time”:“2024-06-27T15:34:14+02:00”,“took”:56834}
{“level”:“warning”,“msg”:“Multiple vector spaces are present, GraphQL Explore and REST API list objects endpoint module include params has been disabled as a result.”,“time”:“2024-06-27T15:34:14+02:00”}
{“action”:“grpc_startup”,“level”:“info”,“msg”:“grpc server listening at [::]:50051”,“time”:“2024-06-27T15:34:14+02:00”}
{“action”:“restapi_management”,“level”:“info”,“msg”:“Serving weaviate at http://127.0.0.1:6666/”,“time”:“2024-06-27T15:34:14+02:00”}
:heavy_check_mark: Connected to Weaviate
:information_source: MPS is available. Using MPS…
:information_source: Setting up components
Process SpawnProcess-1:
Traceback (most recent call last):
File “/Users/?/anaconda3/lib/python3.11/multiprocessing/process.py”, line 314, in _bootstrap
self.run()
File “/Users/?/anaconda3/lib/python3.11/multiprocessing/process.py”, line 108, in run
self._target(*self._args, **self._kwargs)
File “/Users/?/anaconda3/lib/python3.11/site-packages/uvicorn/_subprocess.py”, line 78, in subprocess_started
target(sockets=sockets)
File “/Users/?/anaconda3/lib/python3.11/site-packages/uvicorn/server.py”, line 65, in run
return asyncio.run(self.serve(sockets=sockets))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/asyncio/runners.py”, line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/asyncio/runners.py”, line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “uvloop/loop.pyx”, line 1517, in uvloop.loop.Loop.run_until_complete
File “/Users/?/anaconda3/lib/python3.11/site-packages/uvicorn/server.py”, line 69, in serve
await self._serve(sockets)
File “/Users/?/anaconda3/lib/python3.11/site-packages/uvicorn/server.py”, line 76, in _serve
config.load()
File “/Users/?/anaconda3/lib/python3.11/site-packages/uvicorn/config.py”, line 433, in load
self.loaded_app = import_from_string(self.app)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/site-packages/uvicorn/importer.py”, line 19, in import_from_string
module = importlib.import_module(module_str)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/importlib/init.py”, line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “”, line 1204, in _gcd_import
File “”, line 1176, in _find_and_load
File “”, line 1147, in _find_and_load_unlocked
File “”, line 690, in _load_unlocked
File “”, line 940, in exec_module
File “”, line 241, in _call_with_frames_removed
File “/Users/?/anaconda3/lib/python3.11/site-packages/goldenverba/server/api.py”, line 38, in
setup_managers(manager)
File “/Users/?/anaconda3/lib/python3.11/site-packages/goldenverba/server/util.py”, line 13, in setup_managers
config = load_config(manager)
^^^^^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/site-packages/goldenverba/server/util.py”, line 227, in load_config
return get_config(manager)
^^^^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/site-packages/goldenverba/server/util.py”, line 40, in get_config
“components”: {
^
File “/Users/?/anaconda3/lib/python3.11/site-packages/goldenverba/server/util.py”, line 41, in
reader: readers[reader].get_meta(
^^^^^^^^^^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/site-packages/goldenverba/components/interfaces.py”, line 47, in get_meta
“config”: {_c: self.config[_c].model_dump() for _c in self.config},
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/Users/?/anaconda3/lib/python3.11/site-packages/goldenverba/components/interfaces.py”, line 47, in
“config”: {_c: self.config[_c].model_dump() for _c in self.config},
^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: ‘InputText’ object has no attribute ‘model_dump’

**Comment by L-Huber** [comment]
already posted in the forum, but it did not help:[https://forum.weaviate.io/t/error-while-installing-verba-offline/2839/5](https://forum.weaviate.io/t/error-while-installing-verba-offline/2839/5)

**Comment by thomashacker** [comment]
This might be an issue with your pydantic version. Did you install Verba in a clean environment? If you installed Verba in an environment where pydantic was already installed, this might cause issue.
