### ISSUE TITLE
Install 2.0.0 Branch setup.py errors

### ISSUE THREAD

**Issue by aglobalwander** [weaviate/Verba#248]
Installing 2.0.0 Branch in VSCODE. Getting error pip install git+https://github.com/weaviate/Verba.git@2.0.0
Collecting git+https://github.com/weaviate/Verba.git@2.0.0
  Cloning https://github.com/weaviate/Verba.git (to revision 2.0.0) to /private/var/folders/x3/3g4m2f550996dwrlg7720x340000gp/T/pip-req-build-wwra2xu7
  Running command git clone --filter=blob:none --quiet https://github.com/weaviate/Verba.git /private/var/folders/x3/3g4m2f550996dwrlg7720x340000gp/T/pip-req-build-wwra2xu7
  Running command git checkout -b 2.0.0 --track origin/2.0.0
  Switched to a new branch '2.0.0'
  branch '2.0.0' set up to track 'origin/2.0.0'.
  Resolved https://github.com/weaviate/Verba.git to commit 1f7236ae85e6d0a9ccaefd1fa5f94a694987da42
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in goldenverba setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
          langchain-text==splitters-0.2.2
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by thomashacker** [comment]
Please use the `main` branch to install Verba. `2.0.0` is still under development
