### ISSUE TITLE
Azure OpenAI support

### ISSUE THREAD

**Issue by haltux** [weaviate/Verba#25]
It seems Azure OpenAI is supported by Weaviate but not by Verba so far, it would be great to implement it. Thanks!

**Comment by jcarme** [comment]
I have implemented it myself and submitted a pull request.

**Comment by thomashacker** [comment]
Great idea! And thanks for the PR 🚀  We'll be releasing the new version soon and add the Azure OpenAI support 👍

**Comment by jcarme** [comment]
Thanks! I had a look at the new "data-ingestion-update" and it seems the patch will have to be reworked a little bit. I was planning to have a look at that considering I am very interested in the new features, in particular the data ingestion from the API.

Is the branch already in a usable state?

**Comment by thomashacker** [comment]
If you'd like, you can have a look at the `dev` branch, the data ingestion should be working; it's still missing the retrieval and generation part, but it will be added this week :) I also need to make sure to add documentation about the new architecture and better guidelines for contributing.

**Comment by micuentadecasa** [comment]
Hi, did you updated the code? if yes, how should I modify the .env file?

**Comment by jcarme** [comment]
Hello, no I didn't. The new version is quite different. I had a look and it should not be too difficult, I will try to work on it soon. I will post a message here when done.

**Comment by micuentadecasa** [comment]
Thanks jcarme.

Regards.

**Comment by jcarme** [comment]
It's done. I have created the pull request. https://github.com/weaviate/Verba/pull/66

**Comment by micuentadecasa** [comment]
thanks Jcarme.

Regards.

**Comment by thomashacker** [comment]
Merged the PR adding the support for Azure! https://github.com/weaviate/Verba/pull/67 
Thanks for all the great work! 🚀
