### ISSUE TITLE
Docker installation command on Windows

### ISSUE THREAD

**Issue by rickystanley76** [weaviate/Verba#251]
## Description
use this command 
"docker compose --env-file goldenverba/.env up -d --build" instead of 
"docker compose --env-file .env up -d" while installing using docker to get the updated version of verba on your docker.

It will be great if you update the documentation.

## Is this a bug or a feature?
- [ ] Bug
- [ ] Feature

**Comment by thomashacker** [comment]
Good point! We'll add it to the docs

**Comment by rugveddarwhekar** [comment]
I have created a Pull Request to implement the suggested update. You can find the PR at the following link: https://github.com/weaviate/Verba/pull/255.

Please review the PR, and if you find it beneficial, merge it into the main branch.

Thank you for your time and consideration.

**Comment by thomashacker** [comment]
Added it to the docs, thanks a lot!
