### ISSUE TITLE
AI assistant integration with any website

### ISSUE THREAD

**Issue by Nasreddine** [weaviate/Verba#253]
## Description

I am looking to configure my RAG system using Verba and only integrate chat feature as an assistant in my website.

## Is this a bug or a feature?
- [ ] Bug
- [x] Feature

**Comment by thomashacker** [comment]
We're working on it!

**Comment by thomashacker** [comment]
Closing this, will continue this conversation here (https://github.com/weaviate/Verba/issues/254)
