### ISSUE TITLE
BasicReader doesn't take a path

### ISSUE THREAD

**Issue by CarstenHoyer** [weaviate/Verba#257]
## Description
On Macos running Docker, when I try to use the BasicReader import, it won't accept a path only individual files.

It looks like it should work from this: https://github.com/weaviate/Verba/issues/211#issuecomment-2141857245

## Is this a bug or a feature?
- [x] Bug

## Steps to Reproduce
Use the BasicReader and import files, pick a directory, see that the "Open" button is disabled.

**Comment by CarstenHoyer** [comment]
Maybe the <input type="file" /> could be replaced with https://react-dropzone.js.org - from the example, it looks like it accepts directories.

**Comment by thomashacker** [comment]
Should be fixed in the newest release 😄
