### ISSUE TITLE
Getting started video

### ISSUE THREAD

**Issue by anandbhaskaran** [weaviate/Verba#259]
## Description

Verba is awesome! Readme is cool, but I think it would be more impactful if there is a simplified video tutorial, showcasing how to set it up 

## Is this a bug or a feature?
- [ ] Bug
- [x] Feature

**Comment by thomashacker** [comment]
Agreed, working on that!

**Comment by thomashacker** [comment]
https://www.youtube.com/watch?v=2VCy-YjRRhA&t=40s&ab_channel=Weaviate%E2%80%A2VectorDatabase tada 🥳
