### ISSUE TITLE
Error Code 500 because config object cannot be deleted

### ISSUE THREAD

**Issue by WatKey** [weaviate/Verba#262]
## Description
We have written a browser script to upload file batches via the GitHub Reader functionality. We managed to upload approximately 20'000 files and then encountered the following error:

> (ERROR) Delete object! Unexpected status code: 500, with response body: {'error': [{'message': 'could not delete object from vector repo: delete from index "verba_config": delete local object: shard="Tr4MCNMDRTK5": store is read-only'}]}

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
Whenever we try to import new files via the GitHub Reader, we encounter the above error and are unsure about it's origin and how to solve it.

**Comment by thomashacker** [comment]
Let me know if this error still persists 🚀 Will close this for now
