### ISSUE TITLE
Error WebSocket in WSL2

### ISSUE THREAD

**Issue by univis-f** [weaviate/Verba#265]
## Description
I install goldenverba on WSL with Ubuntu 22.04 and add API_KEY for OpenAI GPT3/GPT4. The server started but after a query i have an error on "ws/generate_stream":

Server log:
INFO:     127.0.0.1:43564 - "POST /chat/completions HTTP/1.1" 404 Not Found
✘ WebSocket Error: Invalid response object from API: '{"detail":"Not
Found"}' (HTTP response code was 404)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/voerba1/lib/python3.11/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
                 ~~~~^^^^^^^^^
KeyError: 'error'


Same configuration with Docker version work.

**Comment by thomashacker** [comment]
Seems like a problem within the openai library. We just released the next update for Verba and replaced the openai library with direct API calls. Upgrading to v2 should fix the problem
