### ISSUE TITLE
Document search

### ISSUE THREAD

**Issue by danielhangan** [weaviate/Verba#269]
## Description
A document search functionality would be a great feature for Verba.
The goal is to find relevant documents based on a text input.

## Additional context
https://qatalog.com/product/
https://dash.dropbox.com/features/universal-search

**Comment by thomashacker** [comment]
The Document Explorer should have a search bar to find documents via Bm25 search, you can find it in the Documents tab 😄

**Comment by SaiAkhil066** [comment]
I cannot see the document explorer button over here, can you help me?

**Comment by thomashacker** [comment]
Hey @SaiAkhil066 , what are you seeing on the UI?
