### ISSUE TITLE
Verba Welcome Page loads every time

### ISSUE THREAD

**Issue by BreakerBaron** [weaviate/Verba#272]
## Description

I installed goldenverba following the instructions (pip install) I created the .env file:
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=llama3
when I start verba everyhting is wokring. The issue only is, I always see the "Welcome to Verba Choose your deployment" Page. When browsing to http://MYIP:8000 How can I avoid this?

## Installation

- [x ] pip install goldenverba
- [ ] pip install from source
- [ ] Docker installation

If you installed via pip, please specify the version:
pip 24.0 from /home/llm/verba_env/lib/python3.12/site-packages/pip (python 3.12)

## Weaviate Deployment

- [x ] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader:
Chunker:
Embedder:
Retriever:
Generator:

**Comment by thomashacker** [comment]
Thanks for the issue! Can you give me more information about the issue you're experiencing? Verba now always starts with the starting page where you can select different deployment options of Weaviate

**Comment by John-Appleseed** [comment]
Verba 2.0.0 forgets deployment selection. Users are hassled to select the correct deployment > Click `Let's Get Started` to use a new or refreshed Verba webpage. Same Issue with Docker installation. 

- Every refresh Verba forgets deployment selection. 
`Welcome to Verba, Choose your deployment` > Local > Click `Let's Get Started` > Verba main page
- Ignores weaviate's custom docker port. 
`Choose your deployment` > Docker > Failed to connect to Weaviate http://weaviate:8080?

**Comment by thomashacker** [comment]
Good point, we'll fix this!

**Comment by thomashacker** [comment]
Closing this for now, continuing conversation here (https://github.com/weaviate/Verba/issues/305)

**Comment by jyapayne** [comment]
The welcome page still loads every time when using docker, even if DEFAULT_DEPLOYMENT is set. DEFAULT_DEPLOYMENT stops needing to select docker, etc, but does not stop the welcome page from showing.
