### ISSUE TITLE
Upgrading from 1.0.3 to 2.0.0 fails

### ISSUE THREAD

**Issue by craigpfeifer** [weaviate/Verba#273]
## Description

I upgraded my verba 1.0.3 install to 2.0.0 and I cannot create a local verba instance. When I click on 'Local' I get the error:

`Failed to connect to Weaviate Collection may not have been created properly.! Unexpected status code: 422, with response body: {'error': [{'message': 'class already exists: found similar class "VERBA_Config"'}]}.`

How can I wipe my existing install or migrate it to 2.0.0?

## Installation

- [ ] pip install goldenverba
- [X] pip install from source
- [ ] Docker installation

If you installed via pip, please specify the version: 24.2

## Weaviate Deployment

- [X] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader: N/A
Chunker: N/A
Embedder: N/A
Retriever: N/A
Generator: N/A

## Steps to Reproduce

1) Install verba 1.0.3
2) import documents , issue queries, etc.
3) pip install verba 2.0.0
4) restart verba
5) access https://loaclhost:8000
6) click on 'local'

**Comment by craigpfeifer** [comment]
One solution for embedded weaviate (nuclear option):
1) go to local storage directory (default is [here](https://weaviate.io/developers/weaviate/installation/embedded#configuration-options))
2) delete all files
3) restart verba `verba restart`
4) reload https://localhost:8000
5) click on local
6) happy verba-ing!

**Comment by thomashacker** [comment]
Good catch! Same happend to me, will add some CLI commands to fix this in the future + documentation.
Thanks a lot for the issue 🚀

**Comment by thomashacker** [comment]
Thanks a lot for the issue, I fixed it in the newest release and added it to the documentation as well 🚀

**Comment by craigpfeifer** [comment]
Awesome, looking forward to testing the new version!
