### ISSUE TITLE
N00b question

### ISSUE THREAD

**Issue by Kaszebe** [weaviate/Verba#274]
This isn't an issue so much as a question about Verba.

Hypothetically speaking....let's say that I upload the user manual for a ficticous machine called the XJ9000 Widgetizer.

I also upload all the documentation, Wikipages, and even some forum threads I scraped from the internet.

Would Verba allow me to use Llama 3.1 70B Instruct as a troubleshooter?

e.g.:

If I accidentally discombobulate the flux capacitor of the XJ9000 Widgetizer, I can load up Verba and say:

_"I am noticing that the capacitor is acting like it's discombobulated. I have pushed the green button and twisted the blue knob precisely 2/4 times. Tell me how to diagnose what is going on and how to fix."_

And then Verba (via Llama 3.1 70B Instuct) will search through all the info I uploaded into the RAG and return with some trouble shooting tips--in addition to the knowledge that Llama 3.1 70B Instuct was trained on by META (XJ9000 Widgetizers are very popular machines).

Or will it just return with the relevant troubleshooting step (verbatim or close to verbatim) from the user manual?

**Comment by thomashacker** [comment]
Interesting question! I think we'll only find out if you test it 😄
