### ISSUE TITLE
Contributing an OpenAPI spec document

### ISSUE THREAD

**Issue by jasonnathan** [weaviate/Verba#275]
## Description

I understand that Verba is very much work in progress and I wanted to create an alternate backend to the current implementation so I generated an openapi spec document and thought I'd share it if it is of any use to you guys?

## Installation

- [x] gh repo clone --fork :)
- [ ] pip install from source
- [ ] Docker installation

## Weaviate Deployment

- [x] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Additional context

Creating an issue before a PR

**Comment by thomashacker** [comment]
Thanks a lot, I'll take a look! 🚀
