### ISSUE TITLE
Can't connect to local Weaviate URL

### ISSUE THREAD

**Issue by samos123** [weaviate/Verba#279]
I went through the code and seems it will always try to use WCS. There is no way to provide a URL to self-hosted Weaviate in Verba.

![image](https://github.com/user-attachments/assets/99e91ec0-1146-49ae-b1b7-57b93ba7b468)
Failed to connect to Weaviate Couldn't connect to Weaviate, check your URL/API KEY: Invalid port: '8080:443'

Trying latest Verba with my local Weaviate installation with local KubeAI install.

I will add more details later.

```
export OPENAI_API_KEY=thisIsIgnored
export WEAVIATE_URL_VERBA=http://localhost:8080
export OPENAI_BASE_URL=http://localhost:8000/openai/v1
verba start --port 8001
```

## Installation

- [X] pip install goldenverba
- [ ] pip install from source
- [ ] Docker installation

If you installed via pip, please specify the version:

## Weaviate Deployment

- [x] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader:
Chunker:
Embedder:
Retriever:
Generator:

**Comment by adchadal** [comment]
reported similar issue https://github.com/weaviate/Verba/issues/282

**Comment by thomashacker** [comment]
Thanks for the issue! We're working on a fix 🚀

**Comment by adchadal** [comment]
> Thanks for the issue! We're working on a fix 🚀

Thank you !

**Comment by tusharrasal** [comment]
same to me

**Comment by thomashacker** [comment]
I added a new deployment option, `Custom,` which should allow you to connect to custom Weaviate instances with custom hosts and ports. Let me know if this works for your Kubernetes setup!
