### ISSUE TITLE
Unable to access weaviate cluster installed on K8S through verba 2.0 

### ISSUE THREAD

**Issue by adchadal** [weaviate/Verba#282]
## Description

I am trying to access verba 2.0 version with weaviate cluster 1.26.3 version installed on kubernetes.

**export params**

export WEAVIATE_API_KEY_VERBA=“password”
export WEAVIATE_URL_VERBA=https://<weaviate-url-k8s>:6383

**Error :**

https://::6383 with Auth
✘ Couldn’t connect to Weaviate, check your URL/API KEY: Invalid port:
‘6383:443’
✘ Failed to connect to Weaviate Couldn’t connect to Weaviate, check
your URL/API KEY: Invalid port: ‘6383:443’
INFO: 10.82.204.17:65400 - “POST /api/connect HTTP/1.1” 400 Bad Request

**Note** : It was working fine with verba 1.0 version ! with weaviate-client v3

## Installation

1. installed python 3.12.4 version 
2. installed weaviate-client v4
3. installed verba using "pip install goldenverba"
4. started the verba server using "verba start --port 27048 --host <verba-host>

<img width="750" alt="image" src="https://github.com/user-attachments/assets/895e961e-d6a4-4797-8028-af149ef22ca4">

(myenv) pip3 freeze|grep verba
goldenverba==2.0.0
(myenv) pip3 freeze|grep weav
weaviate-client==4.7.1
## Weaviate Deployment

Weaviate cluster created using helm charts on kubernetes cluster, http and grpc url's exposed through istio virtual service to access outside the cluster.

## Configuration

Installation issue 

## Steps to Reproduce

Provided the steps i followed for installation and reproducing the issue above.

**Comment by thomashacker** [comment]
I added a new deployment option `Custom` which should allow to connect to custom Weaviate instances with custom hosts + ports. Let me know if this works for your kubernetes setup!

**Comment by adchadal** [comment]
> I added a new deployment option `Custom` which should allow to connect to custom Weaviate instances with custom hosts + ports. Let me know if this works for your kubernetes setup!

Thank you for fixing this !

But when i use pip install goldenverba, it still installs [v2.0.0]. Will there be new version with Custom weaviate instance ?

**Comment by thomashacker** [comment]
For now, I would recommend installing from source since it's the most up-to-date, we'll release `v2.1.0` version to PyPI a bit later

**Comment by thomashacker** [comment]
Hey, I just to released 2.1! 🚀 Let me know if the issue still persists
