### ISSUE TITLE
interface code cannot find  strip_non_letters func  

### ISSUE THREAD

**Issue by DavidSche** [weaviate/Verba#284]
## Description

interface code cannot find  strip_non_letters func  ,I use python 3.11 

![image](https://github.com/user-attachments/assets/3fcd589b-918b-4b28-a935-b51fd2effeb0)

## Installation

- [ ] pip install goldenverba
- [ ] pip install from source
- [ ] Docker installation

If you installed via pip, please specify the version:

## Weaviate Deployment

- [ ] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader:
Chunker:
Embedder:
Retriever:
Generator:

**Comment by thomashacker** [comment]
Good catch, thanks a lot! We'll fix this

**Comment by DavidSche** [comment]
Is there any progress?

**Comment by thomashacker** [comment]
Yes, the legacy code will be removed in the upcoming version! Thanks 🚀

**Comment by thomashacker** [comment]
Should be fixed in the newest version 🚀
