### ISSUE TITLE
Ollama locally with verba

### ISSUE THREAD

**Issue by tusharrasal** [weaviate/Verba#287]
## Installation

- [ ] pip install goldenverba
- [ ] pip install from source

 installed via pip, please specify the version: (24.2)

## Weaviate Deployment

- [ ] Local Deployment

**Comment by tusharrasal** [comment]
✔ Connecting new Client
ℹ Connecting to Weaviate Embedded
✘ Couldn't connect to Weaviate, check your URL/API KEY: <urlopen error
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
issuer certificate (_ssl.c:1000)>
✘ Failed to connect to Weaviate Couldn't connect to Weaviate, check
your URL/API KEY: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed: unable to get local issuer certificate (_ssl.c:1000)>

**Comment by thomashacker** [comment]
This issue is related to `urllib` and not directly `verba`
You can take a look at this thread: https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica

Let me know if this fixes your problem 😄
