### ISSUE TITLE
Firecrawl doesn´t work, have to check api key, but key is correct

### ISSUE THREAD

**Issue by Japhys** [weaviate/Verba#288]
## Description

Signed up for firecrawl. Started off with a free plan to try it out. Got an api key.
In docker compose I added:

      - FIRECRAWL_API_KEY=&FIRECRAWL_API_KEY

In .env file

      - FIRECRAWL_API_KEY=the actualkey from the firecrawl website

When I try to crawl a site I get an error straight away

`Import for website failed: Reader Firecrawl failed with: Firecrawl was not able to load any documents, please check your API Key and settings`

I should be able to do this with the free 500 credits. It's a site with only a 100 pages or so.

There is no way of setting the key via GUI for firecrawl right? Like you can for OpenAI and Cohere.

btw import from pdf in combination with OpenAI api key does work.

## Installation

- [ ] pip install goldenverba
- [ ] pip install from source
- [X] Docker installation

## Weaviate Deployment

- [ ] Local Deployment
- [X] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader: Firecrawl
Chunker: Sentence
Embedder:  OpenAI (this key do work!)
Retriever: Advanced
Generator: OpenAI

## Steps to Reproduce
Whenever I click import selected I get an error straight away. But the key is correct.

**Comment by thomashacker** [comment]
Thanks for the issue! I'll try to reproduce it
If you set environment variables through the `.env` and Verba detects them on startup, they won't be shown to the UI, but I might change this so that you can always edit those.

I'll let you know once we have an update on this 🚀

**Comment by Japhys** [comment]
Made an typo! Embarrassing :(

  - FIRECRAWL_API_KEY=&FIRECRAWL_API_KEY

$$$$$
