### ISSUE TITLE
Tell RAG what to do if no relevant sources were found.

### ISSUE THREAD

**Issue by Japhys** [weaviate/Verba#296]
I am not sure if this has been implemented already but I don't see I way to change this. 

If the RAG does not find relevant answers in the external sources, the model seems to generate an answer based on its internal knowledge and training. For my knowledge base this will not work. It should always say: I am sorry didn't find....blabla

Here are some possible scenarios to consider:

Fallback Mechanism: The model may have a fallback mechanism where it generates an answer based on its internal knowledge if no relevant information is found in the external sources.

Partial Answers: The model can generate an answer that is partially based on the found information and partially on its internal knowledge.

Information about the Lack of Information: The model can inform the user that no relevant information has been found and provide a general answer or ask for more context or specific details.

Hybrid Answers: The model can generate a hybrid answer where it tries to answer the question with the available information and at the same time indicates that not all information may be available.

**Comment by thomashacker** [comment]
Hey, thanks for the issue! You can play around with the `system prompt` to tell the LLM it should not answer if it does not have the required information. You can either modify it in code or through the `Config` tab in the UI. 

Adding more functionality in the generation part of Verba would make sense, I agree, but as of now, there are no future plans to add it unfortunately
