### ISSUE TITLE
Setting/Variable for default deployment type

### ISSUE THREAD

**Issue by N3XPW** [weaviate/Verba#305]
## Description
Add the ability to set a default deployment type for Verba through a configuration setting or environment variable. This feature would allow users to bypass the initial deployment type selection screen when accessing the Verba site, streamlining the user experience for frequent users or specific deployment scenarios.
Proposed implementation:
Introduce a new configuration option or environment variable, e.g., VERBA_DEFAULT_DEPLOYMENT_TYPE.
Allow users to set this variable to one of the available deployment types (e.g., "docker", "custom_local", etc.).
When the Verba site is accessed, if this variable is set, automatically use the specified deployment type without showing the selection screen.
Optionally, provide a way to override this setting for users who occasionally need to choose a different deployment type.

## Additional context
This feature would be particularly useful for:
Development environments where the same deployment type is consistently used.
Production setups where a specific configuration is always required.
Improving workflow efficiency by reducing repetitive selections.
The ability to set a default deployment type would significantly enhance user experience, especially for users who consistently use the same deployment method.

**Comment by thomashacker** [comment]
Great idea, thanks a lot! We'll add this 🚀
