### ISSUE TITLE
Verba won't start on any other port other than 8000

### ISSUE THREAD

**Issue by bw-Deejee** [weaviate/Verba#308]
## Description

Can't run Verba on any other port than 8000. Using the --port flag doesn't help. Page loads with only background color, no content.

## Installation

- [ ] pip install goldenverba
- [x] pip install from source
- [ ] Docker installation

## Weaviate Deployment

- [x] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Steps to Reproduce

Try running Verba on port 8001 using `verba start --port=8001`. Access localhost:8001 and page doesnt load.

## Additional context

-

**Comment by thomashacker** [comment]
Hey, thank you for your issue! It will be fixed in the upcoming `2.1.0` version 🚀
