### ISSUE TITLE
Bunch of Questions

### ISSUE THREAD

**Issue by kllgjc** [weaviate/Verba#309]
## Description

Does this support ingesting existing metadata on PDFs or does it all have to be manual? Can you embed images/use VLM's? does it link back to the original source file if stored in the same location? how do you remove things from the database/update saved locations/re-embed after something is deleted? is there a way to change the size of the points in the 3d view? mapplotlib may be good to integrate instead of the 3d visual. also, is there a way to merge embeddings if you previously embedded so you dont have to redo it?

## Additional context

sorry, a lot of questions

**Comment by thomashacker** [comment]
Hey, thanks for the questions! 

1. Currently, you have to add any metadata manually
2. You cannot embed images 
3. It cannot link back to the original file in your filesystem
4. You can delete documents via the `Document Tab` or you can directly modify the data in your Weaviate instance (depending on the deployment type you chose)
5. You can't change the points size, good idea with matplotlib I'll think about it
6. Right now, if you add data you always have to re-embed it unfortunately
