### ISSUE TITLE
Something went wrong! module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by mhaegeman** [weaviate/Verba#31]
Hi! After following the Install guide, I imported personal documents and started the Verba app but received the following error message:  
```
Something went wrong! module 'openai' has no attribute 'ChatCompletion'
```

**Comment by thomashacker** [comment]
Hey, thanks for the issue! OpenAI changed their API which broke some of the Verba code, we'll make sure to lock the required openai version for now and migrate later. For now, you can try out the `dev` branch, which should have the correct openai version already locked in. The `dev` branch will be merged to `main` next week 👍

**Comment by mhaegeman** [comment]
Awesome thanks for the info!
