### ISSUE TITLE
Issue with installing verba via pip in Macos

### ISSUE THREAD

**Issue by NITHISH-Projects** [weaviate/Verba#313]
Hi everyone,

I am trying to install verba from referring "pip install from source" steps. When executing 'pip install -e .' The installation getting failed and throwing the followin error.
                  
**8 warnings and 8 errors generated.
                  error: command '/usr/bin/clang' failed with exit code 1
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for blis
            Failed to build blis
            ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (blis)
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.**

**Setup Details :**
Macos - sonoma 14.7
python - python 3.13

Kindly please help me in this regard.

Thanks & Regards,
Nithish

**Comment by thomashacker** [comment]
Hey thanks for your issue! Some dependencies of Verba do not support python `3.13.0` yet, you would need to downgrade your python to at least 3.12
