### ISSUE TITLE
Missing Technical.md from the README's Contribution section's link

### ISSUE THREAD

**Issue by Kieran-Sears** [weaviate/Verba#316]
## Description

Just noticed that the documentation for contributing is pointing at a non existent document called [technical.md](https://github.com/weaviate/Verba/TECHNICAL.md).

Where's this live now? And can we update the docs to point to it if it's still relevant? Otherwise, I think it should be removed to avoid confusion.

**Comment by thomashacker** [comment]
Oh, thanks a lot for pointing it out! I'll add it for the upcoming release 🚀

**Comment by thomashacker** [comment]
Done in the latest version! 🚀
