### ISSUE TITLE
Query failed building main branch from source

### ISSUE THREAD

**Issue by redswimmer** [weaviate/Verba#32]
✘ Query failed
Query was not successful! Unexpected status code: 500, with response body: {'code': 500, 'message': 'no consumer registered for application/json'}.

`verba import --path ./data` also returns:

File "C:\Python312\Lib\site-packages\weaviate\schema\crud_schema.py", line 816, in _create_class_with_primitives
 raise UnexpectedStatusCodeException("Create class", response) weaviate.exceptions.UnexpectedStatusCodeException: Create class! Unexpected status code: 500, with response body: {'code': 500, 'message': 'no consumer registered for application/json'}.

**Comment by thomashacker** [comment]
This issue should be fixed with the new 0.3.0 version 🚀  Thanks a lot!
