### ISSUE TITLE
Is there a friendly API for client

### ISSUE THREAD

**Issue by richard-guan-dev** [weaviate/Verba#330]
This is an amazing product that has helped me solve many problems
I would like to ask if Verba has a user-friendly API, such as RESTful, that allows me to use Verba externally through the API.

**Comment by thomashacker** [comment]
Hey, thanks for the kinds words 🚀 We don't have a user-friendly API endpoint at the moment, but we're planning to do so in the future! I'll let you know when we do

**Comment by thomashacker** [comment]
Closing this and keeping this conversation (https://github.com/weaviate/Verba/issues/254)
