### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by shrijit-narkar** [weaviate/Verba#331]
## Description

Do we have any way to manage users?

## Additional context

I have multiple users using Verba. Can I keep a few of them as an admin and others just as users? Do we have any user management feature? I can see that weaviate does provide this functionality but unsure how to use it.

**Comment by thomashacker** [comment]
Great idea! However, Verba is intended and optimized for single local usage only at the moment. There are no plans in the near future to add this, unfortunately 😢
