### ISSUE TITLE
How can i use Verba api with n8n

### ISSUE THREAD

**Issue by mohamedosama113** [weaviate/Verba#336]
I made n8n HTTP request node and try a lot to search with these endpoints but it doesn't work 
/search
/v1/search
/api/v1/search
/api/query
what should i do?

**Comment by thomashacker** [comment]
Hey thanks for the issue! The API is primarily designed and optimized to communicate with the frontend only and it's not recommended to use it outside of that. We'll eventually work on a user-friendly API but as of now I would not recommend using it.
