### ISSUE TITLE
Can not find option Groq for generator

### ISSUE THREAD

**Issue by HEYBOY789** [weaviate/Verba#337]
## Description

I installed verba via pip. But when i go to config, generator settting, i can not find the option to choose Groq

## Installation

- [x ] pip install goldenverba
- [ ] pip install from source
- [ ] Docker installation

If you installed via pip, please specify the version: 2.0.0

## Weaviate Deployment

- [x ] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader: txt
Chunker: Recursive
Embedder: SentenceTransformer
Retriever: Hybrid
Generator:  Groq

## Steps to Reproduce
As you can see in the image, there is no option to use Groq in Generator setting.

![image](https://github.com/user-attachments/assets/4dcd7e25-c5aa-4c06-9561-447a819a2ac2)

**Comment by thomashacker** [comment]
Hey, thanks for your issue! Right now it's only available on the `dev` branch but will be published to the `main` soon, I'll let you know 😄

**Comment by thomashacker** [comment]
Done! 🚀
