### ISSUE TITLE
Query call with protocol GRPC search failed while trying to connect to selfhosted Weaviate Database

### ISSUE THREAD

**Issue by K4l4x** [weaviate/Verba#341]
## Description

We are trying to connect Verba to our self-hosted Weaviate database but are running into an issue. While Verba can locate the self-hosted Weaviate instance, it does not find any documents. It also seems like Verba is unable to properly import the Weaviate database. We can see several collections, including our largest one, "General," with over 20k objects. However, when we try to chat, we receive the following error:

`Query failed: Query call with protocol GRPC search failed with message <AioRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "object search at index verba_embedding_text_embedding_3_large: No properties provided, and no indexed properties found in class"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-12-05T15:36:09.559780182+00:00", grpc_status:2, grpc_message:"object search at index verba_embedding_text_embedding_3_large: No properties provided, and no indexed properties found in class"}">.`

We could not find any relevant information in the documentation or issues.

However importing PDF documents is easily possible.

We would greatly appreciate your help with this. We find your project incredibly exciting and are working in the agricultural industry.

## Installation

We installed Verba via Docker locally on dev machines and on the same instance were our Weaviate database is hosted.

- [ ] pip install goldenverba
- [ ] pip install from source
- [x] Docker installation

If you installed via pip, please specify the version: 2.0.0

## Weaviate Deployment

Using Weaviate version: 1.27.0-rc.0

- [ ] Local Deployment
- [x] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader: None
Chunker: None
Embedder: OpenAI text-embedding-3-large
Retriever: Advanced (In the Verba chat config) or unclear
Generator: OpenAI gpt-4o

## Steps to Reproduce

Connecting to a Docker composed Weaviate Database instance via self-hosted or custom option.

## Additional context

We know that "steps to reproduce" might not be entirely feasible. However, we are happy to provide as much insight as we can and assist with any follow-up questions.

**Comment by thomashacker** [comment]
Hey thanks for the issue. 

Unfortunately, Verba needs the data to be in a specific schema, which is only possible by importing data through the frontend. This means that Verba is not compatible with pre-existing data within a cluster, and there are no plans yet to implement it as it would require a huge re-write of the whole Verba codebase. 

However, we're currently working on another open-source solution that will hopefully replace `Verba` and fix pain points just like these 😄 I'll let you know once we published the new project and sorry for the inconvinience

**Comment by K4l4x** [comment]
Thank you so much for your quick response!

How unfortunate! Nevertheless, we find Weaviate and Verba highly interesting!

We are currently working on our own development, which is similar to Verba, aiming to integrate it with our existing Weaviate vector store. We can imagine contributing to the development of such a solution within the framework of the license you have set. Perhaps there might be interest on your side? If you're interested, we would love to talk about this in a call.

In any way, have a nice day!

**Comment by thomashacker** [comment]
I'll let you know once we released the first version, would love to collaborate on this
