### ISSUE TITLE
Iam not able to communicate with the other PCs when I connected with LAN. 

### ISSUE THREAD

**Issue by SaiAkhil066** [weaviate/Verba#356]
## Installation

- [ ] pip install goldenverba
- [*] pip install from source
- [ ] Docker installation

If you installed via pip, please specify the version:

## Weaviate Deployment

- [* ] Local Deployment
- [ ] Docker Deployment
- [ ] Cloud Deployment

## Configuration

Reader:
Chunker:
Embedder:
Retriever:
Generator:

## Steps to Reproduce
Firstofall, Iam running this project in a VM, so the URL Networking would have some changes, Please suggest me
I have installed Verba freshly from GITHUB.. then exactly same as process given in the README file and then I built npm installations in frontend file and run npm run dev... and in the backend i ran verba start...., in the localhost those are running, But which are binded with the LAN, in those LAN PCs these are not opening, 
Please suggest me what to do with this. Will be very happy If I clear this Issue!!!!

**Comment by thomashacker** [comment]
Hey thanks for the issue, it think it's related to this issue (https://github.com/weaviate/Verba/issues/353)

**Comment by SaiAkhil066** [comment]
Yes it is, What it may be the solution, Please anyone Acknowledge to this, Iam running out of time

**Comment by SaiAkhil066** [comment]
Yes, I got the trick.
firstly, we have to mention server's IP address in api.py and cli.py (fastapi).
Boom it works
