### ISSUE TITLE
Chunks are not imported

### ISSUE THREAD

**Issue by huynq55** [weaviate/Verba#36]
![image](https://github.com/weaviate/Verba/assets/1425348/44cc87d7-698c-407f-a9de-9366e35e0e11)
It said: Imported all chunks
In fact, after checking I see that the chunks are not imported

**Comment by thomashacker** [comment]
Hey @huynq55 , thanks for the issue! Have you tried using the newest version of Verba? We made a lot of changes in the data import and made the ingestion more robust 🚀

**Comment by huynq55** [comment]
Thank you. The picture above is of an older version. I have tried the new version and am truly impressed with the data entry capability on the graphical interface. However, I encounter a problem when entering multiple files at the same time (I have about more than 3000 files with a total size of around 10MB). Therefore, I am manually entering each file.

**Comment by huynq55** [comment]
Occasionally, I encounter the following error while importing files:
![image](https://github.com/weaviate/Verba/assets/1425348/d60c44c8-c74a-45e0-aef5-2f91c6ca5844)

**Comment by huynq55** [comment]
And while importing multiple files
![image](https://github.com/weaviate/Verba/assets/1425348/e986bbf7-83a9-489f-9d54-dc6cc9878995)

**Comment by thomashacker** [comment]
This is interesting, thank you for the information 👍 I will have a look into this!

**Comment by thomashacker** [comment]
Can you give me more information about what type of Weaviate deployment you use? Weaviate Embedded, Docker or WCS (Weaviate Sandbox Cluster)?

Also, what Embedding configuration do you have selected when ingesting the files? Does ingestion work when you try to add one single file?

**Comment by huynq55** [comment]
I'm using WCS, the trial version (expires after 21 days).
I am using OpenAI Ada to ingest files.
Ingestion works fine when I add just one file.
However, occasionally it doesn't work, but if I try ingesting again after a while, it's okay.
I'm leaning towards the possibility that I might have exceeded OpenAI's rate limit?

**Comment by thomashacker** [comment]
I agree; the error handling of Verba definitely needs more work so that we can actually see what the error is 😄 
And yes, when using OpenAI Ada, the API can sometimes fail because OpenAI is either overloaded or there are problems with your key, as you mentioned
