### ISSUE TITLE
missing dependency when install

### ISSUE THREAD

**Issue by Joshua0128** [weaviate/Verba#37]
I use pip to install the goldenverba. after installation it showed.
![Screenshot from 2023-11-14 23-49-16](https://github.com/weaviate/Verba/assets/14936390/2f310685-a767-4e9a-817c-3cd58f30d3da)

the issue fixed after I install the missing package.

**Comment by thomashacker** [comment]
Interesting, thanks for the issue! `chardet` seems to be used by the requests library, I'll have a look and fix the installation package

**Comment by thomashacker** [comment]
Fixed and merged on the `main` branch! It will be included in the `v0.3.1` release! You can install it via cloning the GitHub repo and using `pip install -e .` or wait for the release, which should come soon!
