### ISSUE TITLE
Loading data failed Expecting value: line 2 column 1 (char 1)

### ISSUE THREAD

**Issue by huynq55** [weaviate/Verba#39]
Got this error while importing documents
![image](https://github.com/weaviate/Verba/assets/1425348/6b106364-7f4d-4e69-b1f2-4d7f6cddb92b)

**Comment by huynq55** [comment]
After that, I can't import documents anymore

**Comment by thomashacker** [comment]
Interesting! You can use the interface to delete the loaded document or reset Verba completely (on status page at the bottom). There seems to be a bug within the data ingestion part. We'll have a look into this! 

What kind of data are you ingesting? Are they simple .txt files?

**Comment by huynq55** [comment]
Indeed, my data consists only of .txt files. After rebooting Verba, the program imported everything back normally.
