### ISSUE TITLE
context length exceeded

### ISSUE THREAD

**Issue by gknor** [weaviate/Verba#4]
Hi,
I tried to use my data (text file with 5k lines), but every time I ask for something I get an error:
`Something went wrong! This model's maximum context length is 4097 tokens. However, your messages resulted in 5747 tokens. Please reduce the length of the messages.|`
![image](https://github.com/weaviate/Verba/assets/16681052/a9f1fdbb-463e-4015-9aee-f596d058fd44)

**Comment by gknor** [comment]
It works with 16k model: `verba start --model "gpt-3.5-turbo-16k"`, but in my opinion the exception of too long context should be handled.

**Comment by thomashacker** [comment]
This issue was fixed with the new 0.3.0 version 🚀  Thanks a lot!
