### ISSUE TITLE
Add proper linting

### ISSUE THREAD

**Issue by grski** [weaviate/Verba#42]
The code lacks support for modern linting tools which will enable to code to be more standardised and clean.
Suggested solution: ruff & pre-commit.

**Comment by grski** [comment]
https://github.com/weaviate/Verba/pull/43

**Comment by cam-barts** [comment]
Hello again Verba/Weaviate team. I have bit of experience setting up github actions pipelines to do linting/formatting stuff, and especially with the [megalinter](https://megalinter.io/latest/) project. I think that would be useful for something like this that has both Python and JS components. It could handle linting and formatting, but also some static security checks and even can check for reused code that can be refactored. 

I know based on the Contributing guide that you'd all prefer issue discussion first, so let this be me communicating that I'm interested in taking something like that on for you all. Let me know what you think!

**Comment by thomashacker** [comment]
We'll look into improved linting in future versions! Thanks a lot for the help
