### ISSUE TITLE
Add poetry support

### ISSUE THREAD

**Issue by grski** [weaviate/Verba#44]
Currently poetry is the go-to standard to manage dependencies, builds and virtualenvs. I think it'd be useful to incorporate it.

**Comment by thomashacker** [comment]
Agree! We will look into it, thanks

**Comment by grski** [comment]
@thomashacker if are ok with that I can tackle it

**Comment by thomashacker** [comment]
That'd be great, thanks!

**Comment by kirill-push** [comment]
@thomashacker Hi! Is this issue is still relevant?

**Comment by thomashacker** [comment]
Yes! It is
