### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by grski** [weaviate/Verba#45]
Having CI/CD would allow for automated linting and testing in the pipeline which would make it easier to contribute to the project, ensuring proper Quality, reducing number of bugs and so on.
GitHub Actions would do the job just fine.

**Comment by thomashacker** [comment]
Agree! We're currently working on making the codebase more established and writing automated testing

**Comment by grski** [comment]
@thomashacker I've seen that currently the tests fail, I probably don't know the codebase well enough to fix them, but I can definitely add the CI/CD

**Comment by thomashacker** [comment]
That'd be helpful, thanks! 🚀

**Comment by thomashacker** [comment]
We'll work on proper testing in future versions! Thanks a lot for the good work
