### ISSUE TITLE
Display line breaks in chat

### ISSUE THREAD

**Issue by MartinPicc** [weaviate/Verba#48]
Hi,

Suggestion for a small but nice frontend improvement: add `whitespace-pre-line` as an HTML class in this line:

https://github.com/weaviate/Verba/blob/94a2555b0f0b8adcd2d3adabe29c46d570e8c33d/frontend/components/ChatComponent.tsx#L230

As such, messages in the chat will be displayed with proper line breaks.

With:
![image](https://github.com/weaviate/Verba/assets/35298861/d7339f43-9c3c-4f6d-b65a-98154e28beb0)

Without:
![image](https://github.com/weaviate/Verba/assets/35298861/d5c39c40-a57b-4a02-8b42-569e481491b7)

**Comment by thomashacker** [comment]
Awesome! Thanks, we'll definitely add it to make the Chat UI look better 🚀

**Comment by thomashacker** [comment]
Fixed and merged on the `main` branch! It will be included in the `v0.3.1` release! You can install it by cloning the GitHub repo and using `pip install -e .` or wait for the release, which should come soon!
