### ISSUE TITLE
Add a non-api way to load PDFs with pypdf

### ISSUE THREAD

**Issue by Maro1F431** [weaviate/Verba#49]
Hello !

It would be nice if we could load PDFs (which is for me the main reason to use the app) without the dependency on the Unstructured API.

Why not simply use something like [pydf](https://pypi.org/project/pypdf/) to load PDFs ?

**Comment by thomashacker** [comment]
Great idea! Thanks for the issue 👍 It's already implemented in the latest `main` branch and will be included in the next release. If you want to use PyPDF now, you can install Verba from source

**Comment by thomashacker** [comment]
Thanks for the resource, we'll look into also incorporating them into Verba
