### ISSUE TITLE
Either lock input while previous is processing or disable enter/submit

### ISSUE THREAD

**Issue by alvarobartt** [weaviate/Verba#5]
Hi to whoever is reading this! 🤗 BTW great work with `verba`, I've been playing around with it and I find it really useful

## Issue

I've realised that you can actually send more than one input sequentially while the first one sent is still processing, so I think that you could either lock the input bar so that the users cannot write anything while the previous request is being processed in that session, or just disable the enter/submit so that when trying to send another message a toast message appears saying that you cannot submit sequential inputs, similarly to what any other chatbot out there may be.

Thanks in advance!

**Comment by thomashacker** [comment]
That's a great idea and makes total sense! Thanks a lot
We'll put it on our list ✨

**Comment by thomashacker** [comment]
This issue was fixed with the new 0.3.0 version 🚀  Thanks a lot!
