### ISSUE TITLE
Error: Missing Embedder and Options Not Displayed in 'Add Document

### ISSUE THREAD

**Issue by atifemreyuksel** [weaviate/Verba#51]
I have deployed Verba via Docker, and I can successfully access the frontend side. However, I've encountered an issue where no options are displayed in the "Add document" section. Upon inspecting the Docker logs, I've come across the following error message:
`  
File "/Verba/goldenverba/server/api.py", line 300, in get_components
    config_manager.get_embedder(), embedders[config_manager.get_embedder()]
KeyError: ''
`

Additionally, I've created my own .env file and have added only the Hugging Face API token.

Could you please help me understand why this error is occurring right after the initialization? Is there any crucial installation step that I might have missed?

**Comment by thomashacker** [comment]
Interesting! Thanks for the issue. 
The FastAPI Service creates a config.json which it uses to cache selected components and their configuration. This is a bug, where the config saved an empty string as the embedder component, and now throws an KeyError. I will look into it and fix this! 🚀

**Comment by thomashacker** [comment]
Fixed the issue on the `main` branch, will be included in the coming release! 🚀  You can install from source by cloning the project and installing it via `pip install -e .`

**Comment by hubciorz** [comment]
@thomashacker I'm not sure if it has been fixed. I'm still encountering the same error but now the line number is different.
```
   File "/Users/hubciorz/Verba/goldenverba/server/api.py", line 294, in get_components
    config_manager.get_embedder(), embedders[config_manager.get_embedder()]
                                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ''
```

**Comment by koshyviv** [comment]
Im still getting this issue
