### ISSUE TITLE
 Cohere API Key: no api key found neither in request header:

### ISSUE THREAD

**Issue by micuentadecasa** [weaviate/Verba#54]
Hi, I'm starting to try Verba, I cloned the project, modified the .env file, and installed it with  pip install, but it seems that there is something that I have not done, it is not taking the Keys from the .env file when I use verba start, can you help me?

Regards.

**Comment by thomashacker** [comment]
Thanks for the issue! Are you seeing the Cohere API Key displayed on the status page? Where is your `.env ` and from where are you starting Verba, we might find the problem there 😄

**Comment by thomashacker** [comment]
That's great to hear! How did you solve it?

**Comment by micuentadecasa** [comment]
At the end I used the dockerfile, by the way there is an error in the last
line in the .env, you cannot use underscore.

Regards.
