### ISSUE TITLE
REST API to push external sources

### ISSUE THREAD

**Issue by priamai** [weaviate/Verba#57]
Hi there,
would be nice to have a simple REST API where I can push text from external sources.
For instance I have a large source of documents coming from Youtube captions, Whisper conversations (from audio) and you get the idea.
Would like to see also a basic capability to tag the source so I know where it was coming from: a URL and a list of tags at least.
Cheers!

**Comment by priamai** [comment]
Seems related to this [issue](https://github.com/weaviate/Verba/issues/64) .

**Comment by thomashacker** [comment]
Hey, thanks for your PR! To every batch of documents, you can assign a `document type` tag, these are the ones that will be displayed on the UI when retrieving the chunks. The SimpleReader supports reading in JSON files that are specifically designed for Verba data structure (I should definitely add these information to the README).

They look like this: 
https://github.com/weaviate/verba-weaviate-data/blob/main/data/Video/Authentication%3A%20Overview.json

```json
{"text":"Document Text",
"type":"Your-Source",
"name": "Title", 
"path": "", 
"link": "Link-to-source", 
"timestamp": "", 
"reader": "JSON", 
"meta": {}, 
"chunks": []}
```

Could this help your usecase? Let me know if you have any feedback on this

**Comment by priamai** [comment]
Amazing, can you also make examples on using timestamp, path, meta ?
Can I use chunks if I have pre chunked the text with another model? But what format should I use ?
