### ISSUE TITLE
Add a Langchain QA agent in addition to vector search

### ISSUE THREAD

**Issue by priamai** [weaviate/Verba#58]
Hi there,
what about also adding a Langchain QA agent interface in addition to the standard search?

It should be quite straightforward to add like this example: https://python.langchain.com/docs/use_cases/question_answering/conversational_retrieval_agents

Super powerful!

**Comment by thomashacker** [comment]
Great idea! We'll look into it

**Comment by thomashacker** [comment]
We added LangChain Tokenizers in the newest release, but feel free to create a PR and add it to the newest version. I'll pause this for now
