### ISSUE TITLE
Add Adobe PDF Extract API

### ISSUE THREAD

**Issue by priamai** [weaviate/Verba#59]
Hi there,
I have been working on PDF extraction for some time and nothing beats the Adobe service (well as you know they are the one who invented it).
SDK is here: https://developer.adobe.com/document-services/docs/overview/pdf-extract-api/gettingstarted/#sdk
You get 500 documents per month on free tier so lots of people will enjoy.

PS:
I am not affiliated to Adobe in any way.

**Comment by thomashacker** [comment]
We looked into the Adobe PDF API and decided to not pursue this for now, but thanks for the suggestion!
