### ISSUE TITLE
When Querying from front end : Quickstart: Build from Source

### ISSUE THREAD

**Issue by MHossain-dviz** [weaviate/Verba#6]
✘ Query failed
Query was not successful! Unexpected status code: 422, with response body: {'error': [{'message': 'no graphql provider present, this is most likely because no schema is present. Import a schema first!'}]}.

**Comment by thomashacker** [comment]
Thanks for the issue! This happened because no data was loaded into the Weaviate cluster. To fix this, you can import test data with the `verba import --path "./data"` command.

This needs better error handling, we'll look into this!

**Comment by thomashacker** [comment]
This issue was fixed with the new 0.3.0 version 🚀  Thanks a lot!
