### ISSUE TITLE
Loading data failed Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by PiotrEsse** [weaviate/Verba#61]
Hi, 
Ive followed quick installation from PIP. I use [HuggingFace] version.
I have laptop with 2 GPU (AMD and Nvidia).
Gui starts flawlessly but when I wand to upload any simpliest TXT document, I am getting following error:
```

Vectorizing document chunks:   0%|                                                                                                   | 0/1 [00:00<?, ?it/s]
✘ Loading data failed Expected all tensors to be on the same device,
but found at least two devices, cuda:0 and cpu! (when checking argument for
argument index in method wrapper_CUDA__index_select)
```

Where I should force GPU usage?
Preety please help.

**Comment by marklysze** [comment]
I'm having the same issue with just one GPU (nvidia) when trying to load a text file.

**Comment by thomashacker** [comment]
Thanks for the issue! We're aware of that bug, and should have them fixed in the next release

**Comment by PiotrEsse** [comment]
> Thanks for the issue! We're aware of that bug, and should have them fixed in the next release

Thank You. Do You think theres a way to manually correct it now without waiting for a release?

**Comment by thomashacker** [comment]
Otherwise, you can have a look at the MiniLMEmbedder implementation (https://github.com/weaviate/Verba/blob/main/goldenverba/components/embedding/MiniLMEmbedder.py)

**Comment by PiotrEsse** [comment]
> It should be fixed on the `main` branch. You can install it from source via cloning the project and using `pip install -e .`

Thank You! Its working!

**Comment by thomashacker** [comment]
That's great to hear! Thanks for finding the bug 😄
