### ISSUE TITLE
Document f70ddcbd-b9f7-4f38-9f61-4f6e7604fb86 not found None

### ISSUE THREAD

**Issue by TweedBeetle** [weaviate/Verba#62]
When I try to load the Verba repo using the GithubReader and the path "weaviate/Verba/", i get the error "Document f70ddcbd-b9f7-4f38-9f61-4f6e7604fb86 not found None"

Am I doing something wrong?

**Comment by cam-barts** [comment]
This is the same type of error that shows up when a document is too large to parse, which is the same issue as #50.

**Comment by cfong32** [comment]
I have the same issue when I was trying to ingest any of these pdfs:
2013 Sienna Manuals
•	Owner's Manual (16M, http://s3.amazonaws.com/toyota.site.p01/toyota/manuals/OM45472U/OM45472U.pdf)
•	Owner's Manual Supplement (532K, http://s3.amazonaws.com/toyota.site.p01/toyota/manuals/OMS1013U/OMS1013U.pdf)
Warranty, maintenance and roadside assistance information
•	Auto Access Seat Owner's Manual (1.5M, http://s3.amazonaws.com/toyota.site.p01/toyota/manuals/OM45476U/OM45476U.pdf)
•	Navigation System Owner's Manual (4.7M, http://s3.amazonaws.com/toyota.site.p01/toyota/manuals/OM45475U/OM45475U.pdf)

**Comment by thomashacker** [comment]
This is super helpful, thanks!

**Comment by thomashacker** [comment]
The error handling should be improved with the new v1.0.0 version, let me know if this error persists
