### ISSUE TITLE
Docker doc enhancements

### ISSUE THREAD

**Issue by adamphetamine** [weaviate/Verba#63]
Please consider modifying the Docker instructions a bit

You currently have the following steps

0. Clone the repo
1. Deploy using Docker

Suggest the this might be more informative- as currently written it misses required steps.
Although these steps are documented above, it's not possible to get a working install just from the current Docker section.

1. Clone the repo using `git clone https://github.com/weaviate/Verba.git` 
2. Navigate into the new Verba directory
3. Add a .env file in the root of your Verba folder **or** add your tokens to the compose.yaml file. At a minimum, you must include x,y and z, but a,b and c are optional depending on your chosen feature set. Adding tokens to .env or compose.yaml file is your choice, but a .env may have some security advantages and allows you to run the compose.yaml file with less modifications, allowing easier upgrades in future. (Maybe these can be configured via the GUI? Is that why they aren't mentioned in the Docker section?)
4. run '`docker compare up -d`' and your project should build and run, you can test readiness by using your web browser to navigate to http://localhost:8080 or http://DockerHostIP:8080 where you will see API endpoint details
5. You can then access the web interface at http://localhost:8000 or http://DockerHostIP:8000

Some of this is probably wrong, as my own install isn't yet working.

also under 'Status Page' you say 
'Once configured, you can monitor your Verba installation's health and status via the 'Status Verba' page' 
but you don't indicate how to reach this page... would be helpful to include that path...

**Comment by thomashacker** [comment]
This is great feedback, thanks! We'll make the Installation Guide more clear

**Comment by adamphetamine** [comment]
I'm happy to write the docs if I can get a working install
Currently this won't run -

[https://github.com/weaviate/Verba/blob/main/docker-compose.yml](url)

If someone can tell me what is required to get a minimal working install I may be able to work the rest out...

**Comment by thomashacker** [comment]
Interesting, will look into it. Thanks for the logs

**Comment by thomashacker** [comment]
We added better instructions for the Docker Deployment
