### ISSUE TITLE
Loader loading endlessly, not getting answer of my question

### ISSUE THREAD

**Issue by dhara-seaflux** [weaviate/Verba#65]
I am not getting answer of my question. loader keep loading endlessly. My text document uploaded successfully.
<img width="1394" alt="Screenshot 2023-11-26 at 4 17 46 PM" src="https://github.com/weaviate/Verba/assets/137403824/c9b28727-131f-4ff7-a42e-31157990a239">
![Uploading Screenshot 2023-11-26 at 4.15.22 PM.png…]()

**Comment by thomashacker** [comment]
Thank you for your issue. What to the logs say in your terminal? Maybe there's an issue with your OpenAI access or with OpenAI itself

**Comment by fredrikmalmberg** [comment]
Also having a similar problem. The UI becomes unresponsive after 1 query. Nothing in the terminal but js console shows [Violation] 'message' handler took 110952ms
[Violation] 'message' handler took 111701ms
[Violation] 'input' handler took 111060ms
[Violation] 'input' handler took 112154ms

Tested in both Chrome and Safari.

**Comment by thomashacker** [comment]
Closing this one
