### ISSUE TITLE
Docker-compose: container verba starts but API does not work

### ISSUE THREAD

**Issue by lambdaofgod** [weaviate/Verba#69]
I'm trying to run verba using docker-compose, when I run it (I fixed Dockerfile to use Python 3.10 BTW) I get

```
verba-verba-1     | /usr/local/lib/python3.10/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
verba-verba-1     |   warnings.warn(
verba-verba-1     | INFO:     Will watch for changes in these directories: ['/Verba']
verba-verba-1     | INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
verba-verba-1     | INFO:     Started reloader process [1] using WatchFiles
verba-verba-1     | /usr/local/lib/python3.10/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
verba-verba-1     |   warnings.warn(
verba-verba-1     | /usr/local/lib/python3.10/site-packages/fastapi/openapi/models.py:55: DeprecationWarning: `general_plain_validator_function` is deprecated, use `with_info_plain_validator_function` instead.
verba-verba-1     |   return general_plain_validator_function(cls._validate)
verba-verba-1     | /usr/local/lib/python3.10/site-packages/pydantic_core/core_schema.py:3902: DeprecationWarning: `general_plain_validator_function` is deprecated, use `with_info_plain_validator_function` instead.
verba-verba-1     |   warnings.warn(
verba-verba-1     | INFO:     Started server process [39]
verba-verba-1     | INFO:     Waiting for application startup.
verba-verba-1     | INFO:     Application startup complete.
verba-verba-1     | ⚠ No module named 'torch'
verba-verba-1     | ℹ Setting up client
verba-verba-1     | ℹ No Auth information provided
verba-verba-1     | ✔ Connected to Weaviate
verba-verba-1     | ℹ New Config initialized
verba-verba-1     | ✔ Saved Config
verba-verba-1     | ✔ Set Reader to SimpleReader
verba-verba-1     | ✔ Set Chunker to TokenChunker
verba-verba-1     | ✔ Set Retriever to WindowRetriever
verba-verba-1     | ✔ Saved Config
verba-verba-1     | INFO:     127.0.0.1:45968 - "HEAD / HTTP/1.1" 200 OK
verba-verba-1     | INFO:     127.0.0.1:45976 - "HEAD / HTTP/1.1" 200 OK
```

In spite of this I can't access verba on localhost:8000. I've waited for couple of minutes. The weaviate seems to work and it returns

```
{"links":[{"href":"/v1/meta","name":"Meta information about this instance/cluster"},{"documentationHref":"https://weaviate.io/developers/weaviate/api/rest/schema","href":"/v1/schema","name":"view complete schema"},{"documentationHref":"https://weaviate.io/developers/weaviate/api/rest/schema","href":"/v1/schema{/:className}","name":"CRUD schema"},{"documentationHref":"https://weaviate.io/developers/weaviate/api/rest/objects","href":"/v1/objects{/:id}","name":"CRUD objects"},{"documentationHref":"https://weaviate.io/developers/weaviate/api/rest/classification,https://weaviate.io/developers/weaviate/api/rest/classification#knn-classification","href":"/v1/classifications{/:id}","name":"trigger and view status of classifications"},{"documentationHref":"https://weaviate.io/developers/weaviate/api/rest/well-known#liveness","href":"/v1/.well-known/live","name":"check if Weaviate is live (returns 200 on GET when live)"},{"documentationHref":"https://weaviate.io/developers/weaviate/api/rest/well-known#readiness","href":"/v1/.well-known/ready","name":"check if Weaviate is ready (returns 200 on GET when ready)"},{"documentationHref":"https://weaviate.io/developers/weaviate/api/rest/well-known#openid-configuration","href":"/v1/.well-known/openid-configuration","name":"view link to openid configuration (returns 404 on GET if no openid is configured)"}]}
```

**Comment by recursionbane** [comment]
I have the same issue.

**Comment by jeffreycwitt** [comment]
Pretty similar issue here for me. 

Weaviate is running and reachable, but Verba on 8080 is not reachable. 

It looks like it is starting well and downloading llama models, but then it just seems to hang.


   verba-verba-1     | /usr/local/lib/python3.10/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
  verba-verba-1     |   warnings.warn(
  verba-verba-1     | INFO:     Will watch for changes in these directories: ['/Verba']
  verba-verba-1     | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
  verba-verba-1     | INFO:     Started reloader process [1] using WatchFiles
  verba-verba-1     | /usr/local/lib/python3.10/site-packages/PyPDF2/__init__.py:21: DeprecationWarning: PyPDF2 is deprecated. Please move to the pypdf library instead.
  verba-verba-1     |   warnings.warn(
  verba-verba-1     | /usr/local/lib/python3.10/site-packages/fastapi/openapi/models.py:55: DeprecationWarning: `general_plain_validator_function` is deprecated, use `with_info_plain_validator_function` instead.
  verba-verba-1     |   return general_plain_validator_function(cls._validate)
  verba-verba-1     | /usr/local/lib/python3.10/site-packages/pydantic_core/core_schema.py:3902: DeprecationWarning: `general_plain_validator_function` is deprecated, use `with_info_plain_validator_function` instead.
  verba-verba-1     |   warnings.warn(
  config.json: 100%|██████████| 612/612 [00:00<00:00, 1.62MB/s]
  pytorch_model.bin: 100%|██████████| 90.9M/90.9M [00:01<00:00, 47.3MB/s]
  tokenizer_config.json: 100%|██████████| 350/350 [00:00<00:00, 1.97MB/s]
  vocab.txt: 100%|██████████| 232k/232k [00:00<00:00, 6.68MB/s]
  tokenizer.json: 100%|██████████| 466k/466k [00:00<00:00, 18.3MB/s]
  special_tokens_map.json: 100%|██████████| 112/112 [00:00<00:00, 188kB/s]
  config.json: 100%|██████████| 614/614 [00:00<00:00, 5.54MB/s]
  model.safetensors.index.json: 100%|██████████| 26.8k/26.8k [00:00<00:00, 16.3MB/s]
  model-00001-of-00002.safetensors: 100%|██████████| 9.98G/9.98G [03:28<00:00, 47.8MB/s]
  model-00002-of-00002.safetensors: 100%|██████████| 3.50G/3.50G [01:11<00:00, 48.7MB/s]
  Downloading shards: 100%|██████████| 2/2 [04:40<00:00, 140.41s/it]:11<00:00, 49.2MB/s]


At this point is just seems to get stuck.

I'm running: 
Docker version 24.0.6, build ed223bc (on a mac)
and
Docker Compose version v2.21.0-desktop.1

**Comment by thomashacker** [comment]
We added some fixes to the Docker setup! Could you try again and see if it works now? 🚀

**Comment by thomashacker** [comment]
Closing this one! Let me know if the error persists

**Comment by thomashacker** [comment]
We added a fix to the Dockerfile! Pull the latest changes and try again. The problem was that verba was not correctly exposed

**Comment by kjeldahl** [comment]
Thanks a lot. It works after rebuilding the containers.

```shell
docker compose down
docker compose build
docker compose up
```
