### ISSUE TITLE
GitHub Reader: hard-coded to `main` branch?

### ISSUE THREAD

**Issue by davidrans** [weaviate/Verba#71]
I'm getting the following error when attempting to use the `GithubReader`
![image](https://github.com/weaviate/Verba/assets/806152/956890e3-a34e-419d-83d1-12c5046f99d1)

It looks like maybe the master branch's name is hard-coded to `main`?
https://github.com/weaviate/Verba/blob/45f1ed4640b4df5640ae02d98d6fd4347d9ff248/goldenverba/components/reader/githubreader.py#L101

**Comment by thomashacker** [comment]
Ah, great catch! Yes, the main branch is hardcoded. We'll add the option to select that dynamically! Thanks for the issue

**Comment by thomashacker** [comment]
Has been fixed with this PR https://github.com/weaviate/Verba/pull/98 🚀
