### ISSUE TITLE
Why add document only support text and json files when I have unstructured API?

### ISSUE THREAD

**Issue by priamai** [weaviate/Verba#74]
Hi there,
since I have added the Unstructured API which should support all type of file formats like DOCX and HTML why the Add document just allow text and json files?
Cheers.

**Comment by priamai** [comment]
I think I have to install the full package: https://unstructured-io.github.io/unstructured/installation/full_installation.html

Testing now!

**Comment by priamai** [comment]
Nope that didn't affect the UI at all.

**Comment by thomashacker** [comment]
Agree! We will add more data types for ingestion in the next update

**Comment by thomashacker** [comment]
The newest version should now allow any Unstructured input through the API
