### ISSUE TITLE
Dangerous confusion with ingestion settings

### ISSUE THREAD

**Issue by priamai** [weaviate/Verba#77]
Hi there,
I noticed that the UI doesn't remember what chunker and embedder were used for documents, what if I forget how I ingested my documents 2 months ago, then I add a new set of documents with a different configuration, then I go to search the results will not be accurate.
Can I process the same document with multiple embeddings and chunkers? Does the backend remember that? We should provide that in the UI at least we know how the documents were processed.

I believe also we are in need of a Profile setting where the user can save it's configuration and then it can match the profile with the documents processed with that setting.

Let me know if it makes any sense.

**Comment by thomashacker** [comment]
Agree! There is a lot of improvements that can be done in that aspect! We look into that for the next update

**Comment by thomashacker** [comment]
The newest version is now remembering the settings used previously!
