### ISSUE TITLE
Unable to Compile  v0.3.1 with python 3.12.0

### ISSUE THREAD

**Issue by JPedroGon** [weaviate/Verba#80]
[install log.txt](https://github.com/weaviate/Verba/files/13518150/install.log.txt)

Clone the version tagged v0.3.1 and tried to manually compile it. Log attached.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by yangyuwen-bri** [comment]
i got the same proble

**Comment by yangyuwen-bri** [comment]
i have the same problem, did you solve it?

**Comment by alexbrooker** [comment]
I had the same issue with python 3.12 so I created a virtual env with python 3.11 and the pip install works & runs

**Comment by thomashacker** [comment]
Great catch! We'll fix it 🚀

**Comment by thomashacker** [comment]
Should be fixed with the latest version!
