### ISSUE TITLE
Add Ollama support for local models

### ISSUE THREAD

**Issue by smpnet74** [weaviate/Verba#81]
Many of us are using https://ollama.ai/ to host models locally rather than use an API or service.  It would be fantastic if we could point to a local Ollama endpoint rather than just what is provided currently.

**Comment by priamai** [comment]
This will is related to https://github.com/weaviate/Verba/issues/56 since you can have OLLAMA as one of the backends.

**Comment by AvnerCohen** [comment]
Anyone managed to set this up with `BASE_URL` ?

**Comment by thomashacker** [comment]
Added Ollama support in the newest v1.0.0 version
