### ISSUE TITLE
the documentation tips doesn't show interesting information

### ISSUE THREAD

**Issue by micuentadecasa** [weaviate/Verba#83]
I was able to load a small pdf, and use the gpt3.5 model, the response seems correct, but if I click on the different documents that appear at the top, when they open at right side, I don't see any relationship with the answer, or the question, if you see my screenshot, at the right side there is a green line that doesn't select anything, and what comes after the green line doesn't seem to be related to the question, I was expecting it highlights the part of the text related

<img width="1395" alt="image" src="https://github.com/weaviate/Verba/assets/912298/03438e0a-2c98-4f47-9ed7-6a7f115590cf">

**Comment by priamai** [comment]
Exactly right, this is why I am suggesting this https://github.com/weaviate/Verba/issues/76

**Comment by thomashacker** [comment]
Should be fixed in the newest v1.0.0 version!
