### ISSUE TITLE
can't load environment variables 

### ISSUE THREAD

**Issue by mohanadaffify** [weaviate/Verba#85]
<img width="1198" alt="Screenshot 2023-12-03 at 16 54 40" src="https://github.com/weaviate/Verba/assets/66140534/ec193817-0eab-47d4-94c7-9788b89b1b2e">

I have added the open AI key here but it seems that verba doesn't recognize it . I am building the image using Docker

**Comment by Deathdadev** [comment]
Did you figure this out? I am having the same issue, even though the .env file is in the same directory as the example env was

**Comment by thomashacker** [comment]
If you use Docker, you need to specify new keys in the `docker-compose.yml` file
