### ISSUE TITLE
Add support for AWS Bedrock

### ISSUE THREAD

**Issue by btiernay** [weaviate/Verba#86]
AWS Bedrock now supports many model types and provides convenient model hosting for enterprises. It would be great if Verba could support this out of the box.

**Comment by amphetamarina** [comment]
This is becoming necessary for our company. I could take this issue, write the code for it and open a PR. 

Would just need to check contributing guidelines.

**Comment by thomashacker** [comment]
Great idea! We're looking into that for the next Verba update

**Comment by thomashacker** [comment]
We decided to not include it for the next release, but feel free to create a PR! I'll pause this for now
