### ISSUE TITLE
error C2039: 'use_tracing': is not a member of '_PyCFrame'

### ISSUE THREAD

**Issue by IMAddMan** [weaviate/Verba#88]
Hi, I keep getting error C2039 below, am I missing something obvious? using windows 10, Python 3.12, QuickStart: Deploy with Pip, thanks,

thinc/backends/numpy_ops.cpp(13261): error C2039: 'use_tracing': is not a member of '_PyCFrame'
        C:\Programs\Python\Python312\Include\cpython/pystate.h(67): note: see declaration of '_PyCFrame'
        thinc/backends/numpy_ops.cpp(13365): error C2039: 'use_tracing': is not a member of '_PyCFrame'
        C:\Programs\Python\Python312\Include\cpython/pystate.h(67): note: see declaration of '_PyCFrame'
        thinc/backends/numpy_ops.cpp(13365): fatal error C1003: error count exceeds 100; stopping compilation
        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for thinc
      Failed to build thinc
      ERROR: Could not build wheels for thinc, which is required to install pyproject.toml-based projects
      [end of output]

**Comment by thomashacker** [comment]
Interesting! We're looking into that, thanks for the issue 🚀

**Comment by thomashacker** [comment]
Should be fixed in the newest version! We removed some packages that were causing errors
