### ISSUE TITLE
The future of RALG and RALM and RADIT

### ISSUE THREAD

**Issue by priamai** [weaviate/Verba#90]
Hello,
I want to flag a few recent developments in the field of RAG.

**RA-DIT: Retrieval-Augmented Dual Instruction Tuning**
https://arxiv.org/abs/2310.01352

**Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection**

https://arxiv.org/abs/2310.11511

**REALM: Retrieval-Augmented Language Model Pre-Training**
https://arxiv.org/abs/2002.08909

**Comment by thomashacker** [comment]
This is great! Thanks a lot!
