### ISSUE TITLE
The website can only be accessed through localhost or 127.0.0.1 and cannot be accessed using the IP address. What could be the reason?

### ISSUE THREAD

**Issue by huicewang** [weaviate/Verba#93]
The website can only be accessed through localhost:8000 or 127.0.0.1:8000 and cannot be accessed using the IP address. What could be the reason?

**Comment by bplunkert** [comment]
I am seeing this too: uvicorn listens only on 127.0.0.1, disregarding the host argument. I thought 8540e48 would have fixed it but doesn't seem so.

`INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)`

**Comment by bplunkert** [comment]
I think this was fixed in 8540e48. You should be able to solve it by installing with the "Build from Source (Quickstart)" method instead of the "Deploy with Pip (Quickstart)" method [here](https://github.com/weaviate/Verba?tab=readme-ov-file#-getting-started-with-verba).
