### ISSUE TITLE
Reset Cache and now says Your Verba has no data yet :(|

### ISSUE THREAD

**Issue by aglobalwander** [weaviate/Verba#94]
I am using embedded Weaviate.  Is it persisent storage by default. How do I know if the files are actually there  and how to have Verba see it?

**Comment by thomashacker** [comment]
Thanks for the issue! What deployment option of Weaviate are you using? Local or Hosted on WCS?

**Comment by thomashacker** [comment]
Closing this one, let me know if the error persists
