### ISSUE TITLE
Random OpenAI error while importing data

### ISSUE THREAD

**Issue by maxpv** [weaviate/Verba#95]
Currently when I call `manager.import_data(` I can get the following issue:

```
✘ {'errors': {'error': [{'message': 'update vector: unmarshal response
body: json: cannot unmarshal number into Go struct field
openAIApiError.error.code of type string'}]}, 'status': 'FAILED'}
It seems to be related to OpenAI and happens randomly. Any idea?
```

Maybe bumping OAI's API to the latest would solve the issue?

**Comment by thomashacker** [comment]
Interesting issue! We're working on updating the openai client to the newest version

**Comment by thomashacker** [comment]
We increased the openai api version, let me know if this fixes the issue for you
