### ISSUE TITLE
Syntax Error GraphQL request (1:69) Invalid character escape sequence

### ISSUE THREAD

**Issue by yiranwu0** [weaviate/Verba#97]
Just trying out verba, but I am getting errors like the one in #24. 
I am using verba=0.3.1.

```
✔ Set Reader to SimpleReader
✔ Set Chunker to TokenChunker
✔ Set Embedder to ADAEmbedder
✔ Set Retriever to SimpleRetriever
✔ Set Generator to GPT3Generator
```
I print the errors in `SimpleRetriever`:
<img width="754" alt="Screenshot 2023-12-14 at 9 58 27 PM" src="https://github.com/weaviate/Verba/assets/32823396/93f00d5b-02f2-47de-919a-828ae7f0da20">

{'errors': [{'locations': [{'column': 69, 'line': 1}], 'message': 'Syntax Error GraphQL request (1:69) Invalid character escape sequence: \\\\d.\n\n1: {Get{Chunk_text2vec_openai(hybrid:{query: "\\begin{array} { l l } { \\dfrac { 1 } { x ^ { 3 }", properties: ["text"], fusionType: relativeScoreFusion}autocut: 2){text doc_name chunk_id doc_uuid doc_type _additional {score }}}}\n

**Comment by thomashacker** [comment]
Interesting! What was your query?

**Comment by thomashacker** [comment]
Closing this one for now! Reopen if the error still persists
